// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.117Z
// Collection: adminFiles/$fileId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin-only file storage
 */

/**
 * Handles AdminFiles files (Get Single File based on its ID, null if not found)
 */
export async function getAdminFiles(fileId: string): Promise<FileItem | null> {
  try {
    const rawResult = await getFiles(`adminFiles/${fileId}`);
    if (!rawResult || !Array.isArray(rawResult) || rawResult.length === 0) return null;
    return rawResult[0] as FileItem;
  } catch (error) {
    console.error(`Error getting file AdminFiles: ${formatError(error)}`);
    return null;
  }
}

/**
 * Handles AdminFiles files (Upload/Replace a File and persist it keyed by its ID) To get the file URL use the getAdminFiles function right after this one.
 * @returns A boolean indicating whether the upload succeeded (true) or failed (false). Always check this value to confirm the upload worked.
 */
export async function uploadAdminFiles(fileId: string, file: File): Promise<boolean> {
  try {
    const pathUsed = `adminFiles/${fileId}`;
    const result = await setFile(pathUsed, file);
    return !!result;
  } catch (error) {
    console.error(`Error uploading file AdminFiles: ${formatError(error)}`);
    return false;
  }
}

/**
 * Handles AdminFiles files (Delete File based on its ID)
 * @returns A boolean indicating whether the delete succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteAdminFiles(fileId: string): Promise<boolean> {
  try {
    await setFile(`adminFiles/${fileId}`, null);
    return true;
  } catch (error) {
    console.error(`Error deleting file AdminFiles: ${formatError(error)}`);
    return false;
  }
}

