// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.118Z
// Collection: arenas/$arenaId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Artist Arena room metadata. Each arena is identified by the artist's wallet address and stores display info and song count for the arena chat room.
 */

export interface ArenasRequest {
  artistAddress: AddressType;
  artistName: string;
  coverImage?: string;
  songCount: number | TimeOperation | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface ArenasResponse {
  artistAddress: string;
  artistName: string;
  coverImage?: string;
  songCount: number;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Arenas operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildArenas(arenaId: string, data?: ArenasRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `arenas/${arenaId}`, document: doc };
}

/**
 * Authenticated users can create an arena when an artist uploads their first song. artistAddress must match arenaId. songCount starts at 1. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setArenas(arenaId: string, data?: ArenasRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`arenas/${arenaId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Arenas: ${formatError(error)}`);
    return false;
  }
}

export type ArenasRequestUpdate = Partial<ArenasRequest>;

/**
 * Build a Arenas update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateArenas(arenaId: string, data: ArenasRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `arenas/${arenaId}`, document: doc };
}

/**
 * Only the artist (matching $arenaId), ADMIN_ADDRESS, or PROJECT_VAULT_ADDRESS can update arena metadata like songCount or coverImage. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateArenas(arenaId: string, data: ArenasRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`arenas/${arenaId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Arenas: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can browse available artist arenas.
   (Get Single Item)
 */
export async function getArenas(arenaId: string): Promise<ArenasResponse | null> {
  try {
    const result = await get(`arenas/${arenaId}`);
    return result as ArenasResponse | null;
  } catch (error) {
    console.error(`Error getting Arenas: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Arenas document. (
  Read Operation Details: Public read. Anyone can browse available artist arenas.
  )
 */
export function subscribeArenas(callback: (data: ArenasResponse | null) => void, arenaId: string): Promise<() => Promise<void>> {
  return subscribe(`arenas/${arenaId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ArenasResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Arenas at path '${`arenas/${arenaId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Arenas items from collection arenas
 
  Read Operation Details: Public read. Anyone can browse available artist arenas.
  
 */
export async function getManyArenas(filter: string = ""): Promise<ArenasResponse[]> {
  try {
    const results = await get("arenas", { prompt: filter });
    return Array.isArray(results) ? results as ArenasResponse[] : [];
  } catch (error) {
    console.error(`Error getting Arenas collection at path 'arenas': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Arenas collection at arenas
 
  Read Operation Details: Public read. Anyone can browse available artist arenas.
  
 */
export function subscribeManyArenas(callback: (data: ArenasResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("arenas", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ArenasResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Arenas collection at path '${"arenas"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Arenas items from collection arenas
 
  Read Operation Details: Public read. Anyone can browse available artist arenas.
  
 */
export async function getAllArenas(filter: string = ""): Promise<ArenasResponse[]> {
  try {
    const results = await get("arenas", { prompt: filter });
    return Array.isArray(results) ? results as ArenasResponse[] : [];
  } catch (error) {
    console.error(`Error getting Arenas collection at path 'arenas': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Arenas collection at arenas
 
  Read Operation Details: Public read. Anyone can browse available artist arenas.
  
 */
export function subscribeAllArenas(callback: (data: ArenasResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("arenas", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ArenasResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Arenas collection at path '${"arenas"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Arenas items in collection arenas.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countArenas(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("arenas", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Arenas at path 'arenas': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Arenas items in collection arenas.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateArenas(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("arenas", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Arenas at path 'arenas': ${formatError(error)}`);
    return { value: 0 };
  }
}

