// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.118Z
// Collection: artists/$artistAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Artist profiles with display name, bio, and verification status.
 */

export interface ArtistsRequest {
  name: string;
  bio?: string;
  profileImage?: string;
  walletAddress: AddressType;
  isVerified: boolean;
  creatorWallet?: AddressType;
  bannerImage?: string;
}

export interface ArtistsResponse {
  name: string;
  bio?: string;
  profileImage?: string;
  walletAddress: string;
  isVerified: boolean;
  creatorWallet?: string;
  bannerImage?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Artists operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildArtists(artistAddress: string, data: ArtistsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `artists/${artistAddress}`, document: doc };
}

/**
 * Users can only create their own artist profile. The $artistAddress path param must equal the caller's wallet, and walletAddress field must match. isVerified must be set (defaults to false on frontend). creatorWallet is NOT set at creation - it is populated later by the backend. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setArtists(artistAddress: string, data: ArtistsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`artists/${artistAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Artists: ${formatError(error)}`);
    return false;
  }
}

export type ArtistsRequestUpdate = Partial<ArtistsRequest>;

/**
 * Build a Artists update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateArtists(artistAddress: string, data: ArtistsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `artists/${artistAddress}`, document: doc };
}

/**
 * The artist (matching $artistAddress) can update their own profile fields. ADMIN_ADDRESS and PROJECT_VAULT_ADDRESS can also update artist profiles, primarily for toggling isVerified status and for the backend to populate creatorWallet (the Privy-created embedded Solana wallet pubkey). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateArtists(artistAddress: string, data: ArtistsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`artists/${artistAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Artists: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can view artist profiles.
   (Get Single Item)
 */
export async function getArtists(artistAddress: string): Promise<ArtistsResponse | null> {
  try {
    const result = await get(`artists/${artistAddress}`);
    return result as ArtistsResponse | null;
  } catch (error) {
    console.error(`Error getting Artists: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Artists document. (
  Read Operation Details: Public read. Anyone can view artist profiles.
  )
 */
export function subscribeArtists(callback: (data: ArtistsResponse | null) => void, artistAddress: string): Promise<() => Promise<void>> {
  return subscribe(`artists/${artistAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ArtistsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Artists at path '${`artists/${artistAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Artists items from collection artists
 
  Read Operation Details: Public read. Anyone can view artist profiles.
  
 */
export async function getManyArtists(filter: string = ""): Promise<ArtistsResponse[]> {
  try {
    const results = await get("artists", { prompt: filter });
    return Array.isArray(results) ? results as ArtistsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Artists collection at path 'artists': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Artists collection at artists
 
  Read Operation Details: Public read. Anyone can view artist profiles.
  
 */
export function subscribeManyArtists(callback: (data: ArtistsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("artists", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ArtistsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Artists collection at path '${"artists"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Artists items from collection artists
 
  Read Operation Details: Public read. Anyone can view artist profiles.
  
 */
export async function getAllArtists(filter: string = ""): Promise<ArtistsResponse[]> {
  try {
    const results = await get("artists", { prompt: filter });
    return Array.isArray(results) ? results as ArtistsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Artists collection at path 'artists': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Artists collection at artists
 
  Read Operation Details: Public read. Anyone can view artist profiles.
  
 */
export function subscribeAllArtists(callback: (data: ArtistsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("artists", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ArtistsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Artists collection at path '${"artists"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Artists items in collection artists.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countArtists(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("artists", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Artists at path 'artists': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Artists items in collection artists.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateArtists(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("artists", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Artists at path 'artists': ${formatError(error)}`);
    return { value: 0 };
  }
}

