// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.119Z
// Collection: beamUpRequests/$requestId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Fan-initiated requests to 'beam up' a streaming-only song to a mintable SPL/NFT asset. Tracks who requested the upgrade, optional gas contribution, and approval status from the song artist.
 */

export interface BeamUpRequestsRequest {
  songId: string;
  requesterWallet: AddressType;
  requesterEmail?: string;
  gasTxHash?: string;
  status: string;
  createdAt: number | IncrementOperation | TokenAmount;
}

export interface BeamUpRequestsResponse {
  songId: string;
  requesterWallet: string;
  requesterEmail?: string;
  gasTxHash?: string;
  status: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a BeamUpRequests operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildBeamUpRequests(requestId: string, data: BeamUpRequestsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `beamUpRequests/${requestId}`, document: doc };
}

/**
 * Authenticated users can create a beam-up request for any song. Caller must equal @newData.requesterWallet so users can only file requests on their own behalf. Optional email and gas transaction hash can be attached. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setBeamUpRequests(requestId: string, data: BeamUpRequestsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`beamUpRequests/${requestId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting BeamUpRequests: ${formatError(error)}`);
    return false;
  }
}

export type BeamUpRequestsRequestUpdate = Partial<BeamUpRequestsRequest>;

/**
 * Build a BeamUpRequests update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateBeamUpRequests(requestId: string, data: BeamUpRequestsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `beamUpRequests/${requestId}`, document: doc };
}

/**
 * Two parties can update: (1) the song's artist (matched via get(/songs/<songId>).creator) can approve/reject/complete the request by changing status; (2) the original requester can edit their own request only while status is still 'pending'. The songId field is expected to remain stable; status flows pending -> approved/rejected -> completed. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateBeamUpRequests(requestId: string, data: BeamUpRequestsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`beamUpRequests/${requestId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating BeamUpRequests: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public. Anyone can view beam-up requests to see demand for upgrading streaming songs to mintable assets.
   (Get Single Item)
 */
export async function getBeamUpRequests(requestId: string): Promise<BeamUpRequestsResponse | null> {
  try {
    const result = await get(`beamUpRequests/${requestId}`);
    return result as BeamUpRequestsResponse | null;
  } catch (error) {
    console.error(`Error getting BeamUpRequests: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single BeamUpRequests document. (
  Read Operation Details: Public. Anyone can view beam-up requests to see demand for upgrading streaming songs to mintable assets.
  )
 */
export function subscribeBeamUpRequests(callback: (data: BeamUpRequestsResponse | null) => void, requestId: string): Promise<() => Promise<void>> {
  return subscribe(`beamUpRequests/${requestId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as BeamUpRequestsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to BeamUpRequests at path '${`beamUpRequests/${requestId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many BeamUpRequests items from collection beamUpRequests
 
  Read Operation Details: Public. Anyone can view beam-up requests to see demand for upgrading streaming songs to mintable assets.
  
 */
export async function getManyBeamUpRequests(filter: string = ""): Promise<BeamUpRequestsResponse[]> {
  try {
    const results = await get("beamUpRequests", { prompt: filter });
    return Array.isArray(results) ? results as BeamUpRequestsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BeamUpRequests collection at path 'beamUpRequests': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BeamUpRequests collection at beamUpRequests
 
  Read Operation Details: Public. Anyone can view beam-up requests to see demand for upgrading streaming songs to mintable assets.
  
 */
export function subscribeManyBeamUpRequests(callback: (data: BeamUpRequestsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("beamUpRequests", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BeamUpRequestsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BeamUpRequests collection at path '${"beamUpRequests"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all BeamUpRequests items from collection beamUpRequests
 
  Read Operation Details: Public. Anyone can view beam-up requests to see demand for upgrading streaming songs to mintable assets.
  
 */
export async function getAllBeamUpRequests(filter: string = ""): Promise<BeamUpRequestsResponse[]> {
  try {
    const results = await get("beamUpRequests", { prompt: filter });
    return Array.isArray(results) ? results as BeamUpRequestsResponse[] : [];
  } catch (error) {
    console.error(`Error getting BeamUpRequests collection at path 'beamUpRequests': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in BeamUpRequests collection at beamUpRequests
 
  Read Operation Details: Public. Anyone can view beam-up requests to see demand for upgrading streaming songs to mintable assets.
  
 */
export function subscribeAllBeamUpRequests(callback: (data: BeamUpRequestsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("beamUpRequests", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as BeamUpRequestsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to BeamUpRequests collection at path '${"beamUpRequests"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count BeamUpRequests items in collection beamUpRequests.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countBeamUpRequests(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("beamUpRequests", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting BeamUpRequests at path 'beamUpRequests': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on BeamUpRequests items in collection beamUpRequests.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateBeamUpRequests(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("beamUpRequests", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating BeamUpRequests at path 'beamUpRequests': ${formatError(error)}`);
    return { value: 0 };
  }
}

