// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.118Z
// Collection: gmStreaks/$userAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks daily GM streak for each user. Document ID is the user's wallet address for natural uniqueness. Stores current streak, longest streak, total GMs, and last GM date.
 */

export interface GmStreaksRequest {
  currentStreak: number | TimeOperation | IncrementOperation | TokenAmount;
  lastGmDate: string;
  longestStreak: number | TimeOperation | IncrementOperation | TokenAmount;
  totalGms: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface GmStreaksResponse {
  currentStreak: number;
  lastGmDate: string;
  longestStreak: number;
  totalGms: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a GmStreaks operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildGmStreaks(userAddress: string, data?: GmStreaksRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `gmStreaks/${userAddress}`, document: doc };
}

/**
 * Users create their own streak record on first GM. The $userAddress path param must equal caller's wallet. currentStreak and totalGms should start at 1, longestStreak at 1, and lastGmDate set to today's date string. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setGmStreaks(userAddress: string, data?: GmStreaksRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`gmStreaks/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting GmStreaks: ${formatError(error)}`);
    return false;
  }
}

export type GmStreaksRequestUpdate = Partial<GmStreaksRequest>;

/**
 * Build a GmStreaks update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateGmStreaks(userAddress: string, data: GmStreaksRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `gmStreaks/${userAddress}`, document: doc };
}

/**
 * Users update their own streak record when sending subsequent GMs. Frontend logic handles streak continuation vs reset based on lastGmDate comparison to current date. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateGmStreaks(userAddress: string, data: GmStreaksRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`gmStreaks/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating GmStreaks: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can view GM streak data for any user.
   (Get Single Item)
 */
export async function getGmStreaks(userAddress: string): Promise<GmStreaksResponse | null> {
  try {
    const result = await get(`gmStreaks/${userAddress}`);
    return result as GmStreaksResponse | null;
  } catch (error) {
    console.error(`Error getting GmStreaks: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single GmStreaks document. (
  Read Operation Details: Public read. Anyone can view GM streak data for any user.
  )
 */
export function subscribeGmStreaks(callback: (data: GmStreaksResponse | null) => void, userAddress: string): Promise<() => Promise<void>> {
  return subscribe(`gmStreaks/${userAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as GmStreaksResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to GmStreaks at path '${`gmStreaks/${userAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many GmStreaks items from collection gmStreaks
 
  Read Operation Details: Public read. Anyone can view GM streak data for any user.
  
 */
export async function getManyGmStreaks(filter: string = ""): Promise<GmStreaksResponse[]> {
  try {
    const results = await get("gmStreaks", { prompt: filter });
    return Array.isArray(results) ? results as GmStreaksResponse[] : [];
  } catch (error) {
    console.error(`Error getting GmStreaks collection at path 'gmStreaks': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in GmStreaks collection at gmStreaks
 
  Read Operation Details: Public read. Anyone can view GM streak data for any user.
  
 */
export function subscribeManyGmStreaks(callback: (data: GmStreaksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("gmStreaks", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as GmStreaksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to GmStreaks collection at path '${"gmStreaks"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all GmStreaks items from collection gmStreaks
 
  Read Operation Details: Public read. Anyone can view GM streak data for any user.
  
 */
export async function getAllGmStreaks(filter: string = ""): Promise<GmStreaksResponse[]> {
  try {
    const results = await get("gmStreaks", { prompt: filter });
    return Array.isArray(results) ? results as GmStreaksResponse[] : [];
  } catch (error) {
    console.error(`Error getting GmStreaks collection at path 'gmStreaks': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in GmStreaks collection at gmStreaks
 
  Read Operation Details: Public read. Anyone can view GM streak data for any user.
  
 */
export function subscribeAllGmStreaks(callback: (data: GmStreaksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("gmStreaks", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as GmStreaksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to GmStreaks collection at path '${"gmStreaks"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count GmStreaks items in collection gmStreaks.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countGmStreaks(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("gmStreaks", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting GmStreaks at path 'gmStreaks': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on GmStreaks items in collection gmStreaks.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateGmStreaks(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("gmStreaks", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating GmStreaks at path 'gmStreaks': ${formatError(error)}`);
    return { value: 0 };
  }
}

