// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.118Z
// Collection: packs/$packId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Single 'studio' pack tier with open-amount pricing. Customers choose the SOL amount they want to contribute (not locked to fixed price tiers); NFT count, token amount, and payout splits are configured per-pack by admins.
 */

export interface PacksRequest {
  artistPayout: number | TimeOperation | IncrementOperation | TokenAmount;
  name: string;
  nftCount: number | TimeOperation | IncrementOperation | TokenAmount;
  platformSlice: number | TimeOperation | IncrementOperation | TokenAmount;
  priceSol: number | TimeOperation | IncrementOperation | TokenAmount;
  priceUsd: number | TimeOperation | IncrementOperation | TokenAmount;
  sortIndex: number | IncrementOperation | TokenAmount;
  tokenAmount: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PacksResponse {
  artistPayout: number;
  name: string;
  nftCount: number;
  platformSlice: number;
  priceSol: number;
  priceUsd: number;
  sortIndex: number;
  tokenAmount: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Packs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPacks(packId: string, data: PacksRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `packs/${packId}`, document: doc };
}

/**
 * Only ADMIN_ADDRESS or PROJECT_VAULT_ADDRESS can create pack definitions. Configures the studio tier: priceUsd in cents and priceSol in lamports represent reference/minimum pricing (customers choose the actual SOL amount at purchase time), tokenAmount in base units of the song SPL token, artistPayout and platformSlice in cents, sortIndex controls display ordering. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPacks(packId: string, data: PacksRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`packs/${packId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Packs: ${formatError(error)}`);
    return false;
  }
}

export type PacksRequestUpdate = Partial<PacksRequest>;

/**
 * Build a Packs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePacks(packId: string, data: PacksRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `packs/${packId}`, document: doc };
}

/**
 * Only ADMIN_ADDRESS or PROJECT_VAULT_ADDRESS can update pack definitions. sortIndex controls display ordering. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePacks(packId: string, data: PacksRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`packs/${packId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Packs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can view available pack products with pricing, NFT count, token amounts, and payout splits.
   (Get Single Item)
 */
export async function getPacks(packId: string): Promise<PacksResponse | null> {
  try {
    const result = await get(`packs/${packId}`);
    return result as PacksResponse | null;
  } catch (error) {
    console.error(`Error getting Packs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Packs document. (
  Read Operation Details: Public read. Anyone can view available pack products with pricing, NFT count, token amounts, and payout splits.
  )
 */
export function subscribePacks(callback: (data: PacksResponse | null) => void, packId: string): Promise<() => Promise<void>> {
  return subscribe(`packs/${packId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PacksResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Packs at path '${`packs/${packId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Packs items from collection packs
 
  Read Operation Details: Public read. Anyone can view available pack products with pricing, NFT count, token amounts, and payout splits.
  
 */
export async function getManyPacks(filter: string = ""): Promise<PacksResponse[]> {
  try {
    const results = await get("packs", { prompt: filter });
    return Array.isArray(results) ? results as PacksResponse[] : [];
  } catch (error) {
    console.error(`Error getting Packs collection at path 'packs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Packs collection at packs
 
  Read Operation Details: Public read. Anyone can view available pack products with pricing, NFT count, token amounts, and payout splits.
  
 */
export function subscribeManyPacks(callback: (data: PacksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("packs", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PacksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Packs collection at path '${"packs"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Packs items from collection packs
 
  Read Operation Details: Public read. Anyone can view available pack products with pricing, NFT count, token amounts, and payout splits.
  
 */
export async function getAllPacks(filter: string = ""): Promise<PacksResponse[]> {
  try {
    const results = await get("packs", { prompt: filter });
    return Array.isArray(results) ? results as PacksResponse[] : [];
  } catch (error) {
    console.error(`Error getting Packs collection at path 'packs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Packs collection at packs
 
  Read Operation Details: Public read. Anyone can view available pack products with pricing, NFT count, token amounts, and payout splits.
  
 */
export function subscribeAllPacks(callback: (data: PacksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("packs", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PacksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Packs collection at path '${"packs"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Packs items in collection packs.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPacks(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("packs", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Packs at path 'packs': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Packs items in collection packs.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePacks(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("packs", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Packs at path 'packs': ${formatError(error)}`);
    return { value: 0 };
  }
}

