// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.119Z
// Collection: playlistSongs/$userAddress/songs/$songId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Per-user playlist entries. Each user has exactly ONE playlist site-wide, stored as a flat list of (user, song) entries under their wallet address. One document per (user, song) pair. Entries can be reordered by the owner via the `position` field, but other fields (userAddress, songId, addedAt) are immutable once added.
 */

export interface PlaylistSongsSongsRequest {
  userAddress: AddressType;
  songId: string;
  addedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  position: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PlaylistSongsSongsResponse {
  userAddress: string;
  songId: string;
  addedAt: number;
  position: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PlaylistSongsSongs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPlaylistSongsSongs(userAddress: string, songId: string, data?: PlaylistSongsSongsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `playlistSongs/${userAddress}/songs/${songId}`, document: doc };
}

/**
 * Only the user themselves can add songs to their own playlist. The $userAddress path segment must equal @newData.userAddress, which must equal @user.address. userAddress and songId are immutable (readonly). addedAt is an immutable Unix timestamp in seconds set on creation. The client must supply a `position` (UInt) representing the sort index within the user's playlist (lower = earlier in the queue). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPlaylistSongsSongs(userAddress: string, songId: string, data?: PlaylistSongsSongsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`playlistSongs/${userAddress}/songs/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PlaylistSongsSongs: ${formatError(error)}`);
    return false;
  }
}

export type PlaylistSongsSongsRequestUpdate = Partial<PlaylistSongsSongsRequest>;

/**
 * Build a PlaylistSongsSongs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePlaylistSongsSongs(userAddress: string, songId: string, data: PlaylistSongsSongsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlistSongs/${userAddress}/songs/${songId}`, document: doc };
}

/**
 * Only the owner ($userAddress == @user.address) can update their own playlist entry. Only the `position` field may change — userAddress, songId, and addedAt must remain identical between @data and @newData. Used for reordering songs within the playlist. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePlaylistSongsSongs(userAddress: string, songId: string, data: PlaylistSongsSongsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlistSongs/${userAddress}/songs/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PlaylistSongsSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can view any user's playlist (it shows on their profile). Sort client-side by `position` ascending for queue order.
   (Get Single Item)
 */
export async function getPlaylistSongsSongs(userAddress: string, songId: string): Promise<PlaylistSongsSongsResponse | null> {
  try {
    const result = await get(`playlistSongs/${userAddress}/songs/${songId}`);
    return result as PlaylistSongsSongsResponse | null;
  } catch (error) {
    console.error(`Error getting PlaylistSongsSongs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PlaylistSongsSongs document. (
  Read Operation Details: Public read. Anyone can view any user's playlist (it shows on their profile). Sort client-side by `position` ascending for queue order.
  )
 */
export function subscribePlaylistSongsSongs(callback: (data: PlaylistSongsSongsResponse | null) => void, userAddress: string, songId: string): Promise<() => Promise<void>> {
  return subscribe(`playlistSongs/${userAddress}/songs/${songId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PlaylistSongsSongsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PlaylistSongsSongs at path '${`playlistSongs/${userAddress}/songs/${songId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PlaylistSongsSongs items from collection playlistSongs/${userAddress}/songs
 
  Read Operation Details: Public read. Anyone can view any user's playlist (it shows on their profile). Sort client-side by `position` ascending for queue order.
  
 */
export async function getManyPlaylistSongsSongs(userAddress: string, filter: string = ""): Promise<PlaylistSongsSongsResponse[]> {
  try {
    const results = await get(`playlistSongs/${userAddress}/songs`, { prompt: filter });
    return Array.isArray(results) ? results as PlaylistSongsSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PlaylistSongsSongs collection at path 'playlistSongs/${userAddress}/songs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PlaylistSongsSongs collection at playlistSongs/${userAddress}/songs
 
  Read Operation Details: Public read. Anyone can view any user's playlist (it shows on their profile). Sort client-side by `position` ascending for queue order.
  
 */
export function subscribeManyPlaylistSongsSongs(callback: (data: PlaylistSongsSongsResponse[]) => void, userAddress: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`playlistSongs/${userAddress}/songs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistSongsSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PlaylistSongsSongs collection at path '${`playlistSongs/${userAddress}/songs`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PlaylistSongsSongs items from collection playlistSongs/${userAddress}/songs
 
  Read Operation Details: Public read. Anyone can view any user's playlist (it shows on their profile). Sort client-side by `position` ascending for queue order.
  
 */
export async function getAllPlaylistSongsSongs(userAddress: string, filter: string = ""): Promise<PlaylistSongsSongsResponse[]> {
  try {
    const results = await get(`playlistSongs/*/songs`, { prompt: filter });
    return Array.isArray(results) ? results as PlaylistSongsSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PlaylistSongsSongs collection at path 'playlistSongs/${userAddress}/songs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PlaylistSongsSongs collection at playlistSongs/${userAddress}/songs
 
  Read Operation Details: Public read. Anyone can view any user's playlist (it shows on their profile). Sort client-side by `position` ascending for queue order.
  
 */
export function subscribeAllPlaylistSongsSongs(callback: (data: PlaylistSongsSongsResponse[]) => void, userAddress: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`playlistSongs/*/songs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistSongsSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PlaylistSongsSongs collection at path '${`playlistSongs/*/songs`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PlaylistSongsSongs items in collection playlistSongs/${userAddress}/songs.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPlaylistSongsSongs(userAddress: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`playlistSongs/${userAddress}/songs`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PlaylistSongsSongs at path 'playlistSongs/${userAddress}/songs': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PlaylistSongsSongs items in collection playlistSongs/${userAddress}/songs.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePlaylistSongsSongs(userAddress: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`playlistSongs/${userAddress}/songs`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PlaylistSongsSongs at path 'playlistSongs/${userAddress}/songs': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Only the user themselves can remove songs from their own playlist (the $userAddress path segment must equal @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePlaylistSongsSongs(userAddress: string, songId: string): Promise<boolean> {
  try {
    const succeeded = await set(`playlistSongs/${userAddress}/songs/${songId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PlaylistSongsSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PlaylistSongsSongs for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePlaylistSongsSongs(userAddress: string, songId: string): DocumentOperation {
  return { path: `playlistSongs/${userAddress}/songs/${songId}`, document: null };
}

