// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.118Z
// Collection: shopifyProducts/$productId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Maps Shopify product IDs (or variant IDs) to Lit Studios song IDs. Used by the webhook to determine which song an order purchased, and by the frontend to show Buy with Card links.
 */

export interface ShopifyProductsRequest {
  shopifyProductId: string;
  songId: string;
  shopifyVariantId?: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface ShopifyProductsResponse {
  shopifyProductId: string;
  songId: string;
  shopifyVariantId?: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a ShopifyProducts operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildShopifyProducts(productId: string, data: ShopifyProductsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `shopifyProducts/${productId}`, document: doc };
}

/**
 * Any authenticated wallet can create a mapping document. The document ID is the full Shopify product identifier or another app-chosen mapping key, and createdAt must be provided as a Unix timestamp in seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setShopifyProducts(productId: string, data: ShopifyProductsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`shopifyProducts/${productId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting ShopifyProducts: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read product-to-song mappings so the frontend and backend can resolve Shopify products to Lit Studios songs.
   (Get Single Item)
 */
export async function getShopifyProducts(productId: string): Promise<ShopifyProductsResponse | null> {
  try {
    const result = await get(`shopifyProducts/${productId}`);
    return result as ShopifyProductsResponse | null;
  } catch (error) {
    console.error(`Error getting ShopifyProducts: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single ShopifyProducts document. (
  Read Operation Details: Anyone can read product-to-song mappings so the frontend and backend can resolve Shopify products to Lit Studios songs.
  )
 */
export function subscribeShopifyProducts(callback: (data: ShopifyProductsResponse | null) => void, productId: string): Promise<() => Promise<void>> {
  return subscribe(`shopifyProducts/${productId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ShopifyProductsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to ShopifyProducts at path '${`shopifyProducts/${productId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many ShopifyProducts items from collection shopifyProducts
 
  Read Operation Details: Anyone can read product-to-song mappings so the frontend and backend can resolve Shopify products to Lit Studios songs.
  
 */
export async function getManyShopifyProducts(filter: string = ""): Promise<ShopifyProductsResponse[]> {
  try {
    const results = await get("shopifyProducts", { prompt: filter });
    return Array.isArray(results) ? results as ShopifyProductsResponse[] : [];
  } catch (error) {
    console.error(`Error getting ShopifyProducts collection at path 'shopifyProducts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in ShopifyProducts collection at shopifyProducts
 
  Read Operation Details: Anyone can read product-to-song mappings so the frontend and backend can resolve Shopify products to Lit Studios songs.
  
 */
export function subscribeManyShopifyProducts(callback: (data: ShopifyProductsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("shopifyProducts", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ShopifyProductsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to ShopifyProducts collection at path '${"shopifyProducts"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all ShopifyProducts items from collection shopifyProducts
 
  Read Operation Details: Anyone can read product-to-song mappings so the frontend and backend can resolve Shopify products to Lit Studios songs.
  
 */
export async function getAllShopifyProducts(filter: string = ""): Promise<ShopifyProductsResponse[]> {
  try {
    const results = await get("shopifyProducts", { prompt: filter });
    return Array.isArray(results) ? results as ShopifyProductsResponse[] : [];
  } catch (error) {
    console.error(`Error getting ShopifyProducts collection at path 'shopifyProducts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in ShopifyProducts collection at shopifyProducts
 
  Read Operation Details: Anyone can read product-to-song mappings so the frontend and backend can resolve Shopify products to Lit Studios songs.
  
 */
export function subscribeAllShopifyProducts(callback: (data: ShopifyProductsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("shopifyProducts", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ShopifyProductsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to ShopifyProducts collection at path '${"shopifyProducts"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count ShopifyProducts items in collection shopifyProducts.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countShopifyProducts(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("shopifyProducts", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting ShopifyProducts at path 'shopifyProducts': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on ShopifyProducts items in collection shopifyProducts.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateShopifyProducts(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("shopifyProducts", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating ShopifyProducts at path 'shopifyProducts': ${formatError(error)}`);
    return { value: 0 };
  }
}

