// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.119Z
// Collection: socialLinks/$storageKey
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Social account linking records created by backend OAuth flow
 */

export interface SocialLinksRequest {
  wallet: AddressType;
  provider: string;
  profile: string;
  linkedAt: number | IncrementOperation | TokenAmount;
}

export interface SocialLinksResponse {
  wallet: string;
  provider: string;
  profile: string;
  linkedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a SocialLinks operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSocialLinks(storageKey: string, data: SocialLinksRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `socialLinks/${storageKey}`, document: doc };
}

/**
 * Backend-only creation via PROJECT_VAULT_ADDRESS. Stores wallet, provider, profile JSON, and linkedAt timestamp. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSocialLinks(storageKey: string, data: SocialLinksRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`socialLinks/${storageKey}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SocialLinks: ${formatError(error)}`);
    return false;
  }
}

export type SocialLinksRequestUpdate = Partial<SocialLinksRequest>;

/**
 * Build a SocialLinks update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateSocialLinks(storageKey: string, data: SocialLinksRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `socialLinks/${storageKey}`, document: doc };
}

/**
 * Backend-only updates via PROJECT_VAULT_ADDRESS. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateSocialLinks(storageKey: string, data: SocialLinksRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`socialLinks/${storageKey}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating SocialLinks: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Users can read their own social links by wallet address match, or backend can read via PROJECT_VAULT_ADDRESS.
   (Get Single Item)
 */
export async function getSocialLinks(storageKey: string): Promise<SocialLinksResponse | null> {
  try {
    const result = await get(`socialLinks/${storageKey}`);
    return result as SocialLinksResponse | null;
  } catch (error) {
    console.error(`Error getting SocialLinks: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SocialLinks document. (
  Read Operation Details: Users can read their own social links by wallet address match, or backend can read via PROJECT_VAULT_ADDRESS.
  )
 */
export function subscribeSocialLinks(callback: (data: SocialLinksResponse | null) => void, storageKey: string): Promise<() => Promise<void>> {
  return subscribe(`socialLinks/${storageKey}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SocialLinksResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SocialLinks at path '${`socialLinks/${storageKey}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SocialLinks items from collection socialLinks
 
  Read Operation Details: Users can read their own social links by wallet address match, or backend can read via PROJECT_VAULT_ADDRESS.
  
 */
export async function getManySocialLinks(filter: string = ""): Promise<SocialLinksResponse[]> {
  try {
    const results = await get("socialLinks", { prompt: filter });
    return Array.isArray(results) ? results as SocialLinksResponse[] : [];
  } catch (error) {
    console.error(`Error getting SocialLinks collection at path 'socialLinks': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SocialLinks collection at socialLinks
 
  Read Operation Details: Users can read their own social links by wallet address match, or backend can read via PROJECT_VAULT_ADDRESS.
  
 */
export function subscribeManySocialLinks(callback: (data: SocialLinksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("socialLinks", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SocialLinksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SocialLinks collection at path '${"socialLinks"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SocialLinks items from collection socialLinks
 
  Read Operation Details: Users can read their own social links by wallet address match, or backend can read via PROJECT_VAULT_ADDRESS.
  
 */
export async function getAllSocialLinks(filter: string = ""): Promise<SocialLinksResponse[]> {
  try {
    const results = await get("socialLinks", { prompt: filter });
    return Array.isArray(results) ? results as SocialLinksResponse[] : [];
  } catch (error) {
    console.error(`Error getting SocialLinks collection at path 'socialLinks': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SocialLinks collection at socialLinks
 
  Read Operation Details: Users can read their own social links by wallet address match, or backend can read via PROJECT_VAULT_ADDRESS.
  
 */
export function subscribeAllSocialLinks(callback: (data: SocialLinksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("socialLinks", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SocialLinksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SocialLinks collection at path '${"socialLinks"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Backend-only deletion via PROJECT_VAULT_ADDRESS.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteSocialLinks(storageKey: string): Promise<boolean> {
  try {
    const succeeded = await set(`socialLinks/${storageKey}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting SocialLinks: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for SocialLinks for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteSocialLinks(storageKey: string): DocumentOperation {
  return { path: `socialLinks/${storageKey}`, document: null };
}

