// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.117Z
// Collection: songs/$songId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Core song token collection. Each song is launched as a tradable SPL token via PumpFunPlugin with automatic bonding curve.
 */

export interface SongsRequest {
  name: string;
  symbol: string;
  uri: string;
  creator: AddressType;
  audiusStreamUrl?: string;
  audiusTrackId?: string;
  albumId?: string;
  slotNumber?: number | TimeOperation | IncrementOperation | TokenAmount;
  isPrivate?: boolean;
  graduated?: boolean;
  graduatedAt?: number | TimeOperation | IncrementOperation | TokenAmount;
  teaserImageUrl?: string;
  graduationReserveBps?: number | TimeOperation | IncrementOperation | TokenAmount;
  assetType?: string;
  mintStatus?: string;
  hasSplToken?: boolean;
  beamUpEnabled?: boolean;
  beamUpRequestCount?: number | IncrementOperation | TokenAmount;
  firstBeamerWallet?: string;
  firstBeamerEmail?: string;
  mintAddress?: string;
  pairCurrency?: string;
  paused?: boolean;
  hidden?: boolean;
  swapEligible?: boolean;
}

export interface SongsResponse {
  name: string;
  symbol: string;
  uri: string;
  creator: string;
  audiusStreamUrl?: string;
  audiusTrackId?: string;
  albumId?: string;
  slotNumber?: number;
  isPrivate?: boolean;
  graduated?: boolean;
  graduatedAt?: number;
  teaserImageUrl?: string;
  graduationReserveBps?: number;
  assetType?: string;
  mintStatus?: string;
  hasSplToken?: boolean;
  beamUpEnabled?: boolean;
  beamUpRequestCount?: number;
  firstBeamerWallet?: string;
  firstBeamerEmail?: string;
  mintAddress?: string;
  pairCurrency?: string;
  paused?: boolean;
  hidden?: boolean;
  swapEligible?: boolean;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a Songs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongs(songId: string, data?: SongsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}`, document: doc };
}

/**
 * Authenticated users can create songs. Creators cannot set swapEligible to true (admin-only). Admin, project vault, and operations wallet have full create access. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongs(songId: string, data?: SongsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Songs: ${formatError(error)}`);
    return false;
  }
}

export type SongsRequestUpdate = Partial<SongsRequest>;

/**
 * Build a Songs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateSongs(songId: string, data: SongsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `songs/${songId}`, document: doc };
}

/**
 * Creator or admin can update. Creators cannot set swapEligible to true (admin-only). Admin, project vault, and operations wallet have full update access. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateSongs(songId: string, data: SongsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`songs/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Songs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can view song metadata.
   (Get Single Item)
 */
export async function getSongs(songId: string): Promise<SongsResponse | null> {
  try {
    const result = await get(`songs/${songId}`);
    return result as SongsResponse | null;
  } catch (error) {
    console.error(`Error getting Songs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Songs document. (
  Read Operation Details: Public read. Anyone can view song metadata.
  )
 */
export function subscribeSongs(callback: (data: SongsResponse | null) => void, songId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Songs at path '${`songs/${songId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Songs items from collection songs
 
  Read Operation Details: Public read. Anyone can view song metadata.
  
 */
export async function getManySongs(filter: string = ""): Promise<SongsResponse[]> {
  try {
    const results = await get("songs", { prompt: filter });
    return Array.isArray(results) ? results as SongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Songs collection at path 'songs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Songs collection at songs
 
  Read Operation Details: Public read. Anyone can view song metadata.
  
 */
export function subscribeManySongs(callback: (data: SongsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("songs", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Songs collection at path '${"songs"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Songs items from collection songs
 
  Read Operation Details: Public read. Anyone can view song metadata.
  
 */
export async function getAllSongs(filter: string = ""): Promise<SongsResponse[]> {
  try {
    const results = await get("songs", { prompt: filter });
    return Array.isArray(results) ? results as SongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Songs collection at path 'songs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Songs collection at songs
 
  Read Operation Details: Public read. Anyone can view song metadata.
  
 */
export function subscribeAllSongs(callback: (data: SongsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("songs", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Songs collection at path '${"songs"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Songs items in collection songs.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongs(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("songs", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Songs at path 'songs': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Songs items in collection songs.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongs(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("songs", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Songs at path 'songs': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getTokenMintAddress" query on Songs.
 * Query Logic: @TokenPlugin.getTokenMintAddress($songId, @data.name, @data.symbol)
 */
export async function runGetTokenMintAddressQueryForSongs(songId: string, ): Promise<string> {
  try {
    const result = await runQuery(`songs/${songId}`, "getTokenMintAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getTokenMintAddress" on Songs: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getBondingCurveProgress" query on Songs.
 * Query Logic: @PumpFunPlugin.getBondingCurveProgress(@TokenPlugin.getTokenMintAddress($songId, @data.name, @data.symbol))
 */
export async function runGetBondingCurveProgressQueryForSongs(songId: string, ): Promise<number> {
  try {
    const result = await runQuery(`songs/${songId}`, "getBondingCurveProgress", {});
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getBondingCurveProgress" on Songs: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getCreatorFee" query on Songs.
 * Query Logic: @PumpFunPlugin.getCreatorFee(@TokenPlugin.getTokenMintAddress($songId, @data.name, @data.symbol))
 */
export async function runGetCreatorFeeQueryForSongs(songId: string, ): Promise<number> {
  try {
    const result = await runQuery(`songs/${songId}`, "getCreatorFee", {});
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getCreatorFee" on Songs: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "getTokenBalance" query on Songs. */
interface SongsGetTokenBalanceArgs {
  walletAddress: string;
}

/**
 * Runs the "getTokenBalance" query on Songs.
 * Query Logic: @TokenPlugin.getBalance(@newData.walletAddress, @TokenPlugin.getTokenMintAddress($songId, @data.name, @data.symbol))
 */
export async function runGetTokenBalanceQueryForSongs(songId: string, args: SongsGetTokenBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`songs/${songId}`, "getTokenBalance", args);
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getTokenBalance" on Songs: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getSolPriceUsd" query on Songs.
 * Query Logic: @PriceFeedPlugin.getPriceFeed(@PriceFeedPlugin.SOL)
 */
export async function runGetSolPriceUsdQueryForSongs(songId: string, ): Promise<number> {
  try {
    const result = await runQuery(`songs/${songId}`, "getSolPriceUsd", {});
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getSolPriceUsd" on Songs: ${formatError(error)}`);
    throw error;
  }
}


/**
 * Buy or sell song tokens via Jupiter aggregator. Supports trading both on bonding curve and after graduation.
 */

export interface SongsSwapsRequest {
  mint: AddressType;
  amt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsSwapsResponse {
  mint: string;
  amt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsSwaps operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsSwaps(songId: string, swapId: string, data?: SongsSwapsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/swaps/${swapId}`, document: doc };
}

/**
 * Any user can swap when PLATFORM_PAUSED is false and the song's paused field is not true. Set mint to @constants.SOL to buy song tokens with SOL, or set mint to the song token mint address to sell tokens for SOL. amt is in the smallest unit of the input token (lamports for SOL). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsSwaps(songId: string, swapId: string, data?: SongsSwapsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/swaps/${swapId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsSwaps: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read.
   (Get Single Item)
 */
export async function getSongsSwaps(songId: string, swapId: string): Promise<SongsSwapsResponse | null> {
  try {
    const result = await get(`songs/${songId}/swaps/${swapId}`);
    return result as SongsSwapsResponse | null;
  } catch (error) {
    console.error(`Error getting SongsSwaps: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsSwaps document. (
  Read Operation Details: Public read.
  )
 */
export function subscribeSongsSwaps(callback: (data: SongsSwapsResponse | null) => void, songId: string, swapId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/swaps/${swapId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsSwapsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsSwaps at path '${`songs/${songId}/swaps/${swapId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsSwaps items from collection songs/${songId}/swaps
 
  Read Operation Details: Public read.
  
 */
export async function getManySongsSwaps(songId: string, filter: string = ""): Promise<SongsSwapsResponse[]> {
  try {
    const results = await get(`songs/${songId}/swaps`, { prompt: filter });
    return Array.isArray(results) ? results as SongsSwapsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsSwaps collection at path 'songs/${songId}/swaps': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsSwaps collection at songs/${songId}/swaps
 
  Read Operation Details: Public read.
  
 */
export function subscribeManySongsSwaps(callback: (data: SongsSwapsResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/swaps`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsSwapsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsSwaps collection at path '${`songs/${songId}/swaps`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsSwaps items from collection songs/${songId}/swaps
 
  Read Operation Details: Public read.
  
 */
export async function getAllSongsSwaps(songId: string, filter: string = ""): Promise<SongsSwapsResponse[]> {
  try {
    const results = await get(`songs/*/swaps`, { prompt: filter });
    return Array.isArray(results) ? results as SongsSwapsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsSwaps collection at path 'songs/${songId}/swaps': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsSwaps collection at songs/${songId}/swaps
 
  Read Operation Details: Public read.
  
 */
export function subscribeAllSongsSwaps(callback: (data: SongsSwapsResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/swaps`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsSwapsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsSwaps collection at path '${`songs/*/swaps`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsSwaps items in collection songs/${songId}/swaps.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsSwaps(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/swaps`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsSwaps at path 'songs/${songId}/swaps': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsSwaps items in collection songs/${songId}/swaps.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsSwaps(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/swaps`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsSwaps at path 'songs/${songId}/swaps': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Buy song tokens directly on bonding curve with exact SOL input amount.
 */

export interface SongsBuysRequest {
  solAmt: number | TimeOperation | IncrementOperation | TokenAmount;
  slip: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsBuysResponse {
  solAmt: number;
  slip: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsBuys operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsBuys(songId: string, buyId: string, data?: SongsBuysRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/buys/${buyId}`, document: doc };
}

/**
 * Any user can buy song tokens on bonding curve when PLATFORM_PAUSED is false and the song's paused field is not true. solAmt is in lamports (1 SOL = 1000000000 lamports). slip is slippage in basis points (500 = 5%). Works only while token is on bonding curve (before graduation). A 2% platform fee (PLATFORM_FEE_BPS / 10000) in SOL is automatically transferred from the buyer to PROJECT_VAULT_ADDRESS (OPERATIONS_WALLET / infra fee wallet) after each buy. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsBuys(songId: string, buyId: string, data?: SongsBuysRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/buys/${buyId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsBuys: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read.
   (Get Single Item)
 */
export async function getSongsBuys(songId: string, buyId: string): Promise<SongsBuysResponse | null> {
  try {
    const result = await get(`songs/${songId}/buys/${buyId}`);
    return result as SongsBuysResponse | null;
  } catch (error) {
    console.error(`Error getting SongsBuys: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsBuys document. (
  Read Operation Details: Public read.
  )
 */
export function subscribeSongsBuys(callback: (data: SongsBuysResponse | null) => void, songId: string, buyId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/buys/${buyId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsBuysResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsBuys at path '${`songs/${songId}/buys/${buyId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsBuys items from collection songs/${songId}/buys
 
  Read Operation Details: Public read.
  
 */
export async function getManySongsBuys(songId: string, filter: string = ""): Promise<SongsBuysResponse[]> {
  try {
    const results = await get(`songs/${songId}/buys`, { prompt: filter });
    return Array.isArray(results) ? results as SongsBuysResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsBuys collection at path 'songs/${songId}/buys': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsBuys collection at songs/${songId}/buys
 
  Read Operation Details: Public read.
  
 */
export function subscribeManySongsBuys(callback: (data: SongsBuysResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/buys`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsBuysResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsBuys collection at path '${`songs/${songId}/buys`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsBuys items from collection songs/${songId}/buys
 
  Read Operation Details: Public read.
  
 */
export async function getAllSongsBuys(songId: string, filter: string = ""): Promise<SongsBuysResponse[]> {
  try {
    const results = await get(`songs/*/buys`, { prompt: filter });
    return Array.isArray(results) ? results as SongsBuysResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsBuys collection at path 'songs/${songId}/buys': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsBuys collection at songs/${songId}/buys
 
  Read Operation Details: Public read.
  
 */
export function subscribeAllSongsBuys(callback: (data: SongsBuysResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/buys`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsBuysResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsBuys collection at path '${`songs/*/buys`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsBuys items in collection songs/${songId}/buys.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsBuys(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/buys`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsBuys at path 'songs/${songId}/buys': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsBuys items in collection songs/${songId}/buys.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsBuys(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/buys`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsBuys at path 'songs/${songId}/buys': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Collect accumulated bonding curve creator fees for a song token.
 */

export interface SongsCollectFeesRequest {

}

export interface SongsCollectFeesResponse {

  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsCollectFees operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsCollectFees(songId: string, feeId: string, data?: SongsCollectFeesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/collectFees/${feeId}`, document: doc };
}

/**
 * Permissionless when PLATFORM_PAUSED is false and the song's paused field is not true. Derives creator from the onchain song document and sends accumulated SOL creator fees to the artist's wallet. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsCollectFees(songId: string, feeId: string, data?: SongsCollectFeesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/collectFees/${feeId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsCollectFees: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read.
   (Get Single Item)
 */
export async function getSongsCollectFees(songId: string, feeId: string): Promise<SongsCollectFeesResponse | null> {
  try {
    const result = await get(`songs/${songId}/collectFees/${feeId}`);
    return result as SongsCollectFeesResponse | null;
  } catch (error) {
    console.error(`Error getting SongsCollectFees: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsCollectFees document. (
  Read Operation Details: Public read.
  )
 */
export function subscribeSongsCollectFees(callback: (data: SongsCollectFeesResponse | null) => void, songId: string, feeId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/collectFees/${feeId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsCollectFeesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsCollectFees at path '${`songs/${songId}/collectFees/${feeId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsCollectFees items from collection songs/${songId}/collectFees
 
  Read Operation Details: Public read.
  
 */
export async function getManySongsCollectFees(songId: string, filter: string = ""): Promise<SongsCollectFeesResponse[]> {
  try {
    const results = await get(`songs/${songId}/collectFees`, { prompt: filter });
    return Array.isArray(results) ? results as SongsCollectFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsCollectFees collection at path 'songs/${songId}/collectFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsCollectFees collection at songs/${songId}/collectFees
 
  Read Operation Details: Public read.
  
 */
export function subscribeManySongsCollectFees(callback: (data: SongsCollectFeesResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/collectFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsCollectFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsCollectFees collection at path '${`songs/${songId}/collectFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsCollectFees items from collection songs/${songId}/collectFees
 
  Read Operation Details: Public read.
  
 */
export async function getAllSongsCollectFees(songId: string, filter: string = ""): Promise<SongsCollectFeesResponse[]> {
  try {
    const results = await get(`songs/*/collectFees`, { prompt: filter });
    return Array.isArray(results) ? results as SongsCollectFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsCollectFees collection at path 'songs/${songId}/collectFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsCollectFees collection at songs/${songId}/collectFees
 
  Read Operation Details: Public read.
  
 */
export function subscribeAllSongsCollectFees(callback: (data: SongsCollectFeesResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/collectFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsCollectFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsCollectFees collection at path '${`songs/*/collectFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsCollectFees items in collection songs/${songId}/collectFees.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsCollectFees(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/collectFees`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsCollectFees at path 'songs/${songId}/collectFees': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsCollectFees items in collection songs/${songId}/collectFees.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsCollectFees(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/collectFees`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsCollectFees at path 'songs/${songId}/collectFees': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Passthrough buyer airdrop transfer from the project vault to a recipient wallet for Shopify fulfillment workflows.
 */

export interface SongsAirdropsRequest {
  recipient: AddressType;
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsAirdropsResponse {
  recipient: string;
  amount: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsAirdrops operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsAirdrops(songId: string, airdropId: string, data?: SongsAirdropsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/airdrops/${airdropId}`, document: doc };
}

/**
 * ADMIN_ADDRESS or PROJECT_VAULT_ADDRESS can trigger a buyer airdrop payout for a song purchase. recipient is the destination wallet and amount is the song token amount in the token's smallest base units; the passthrough hook transfers the song-specific SPL token mint derived from the parent song document from PROJECT_VAULT_ADDRESS to the recipient without storing a permanent record. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsAirdrops(songId: string, airdropId: string, data?: SongsAirdropsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/airdrops/${airdropId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsAirdrops: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can inspect buyer airdrop requests and outcomes.
   (Get Single Item)
 */
export async function getSongsAirdrops(songId: string, airdropId: string): Promise<SongsAirdropsResponse | null> {
  try {
    const result = await get(`songs/${songId}/airdrops/${airdropId}`);
    return result as SongsAirdropsResponse | null;
  } catch (error) {
    console.error(`Error getting SongsAirdrops: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsAirdrops document. (
  Read Operation Details: Public read. Anyone can inspect buyer airdrop requests and outcomes.
  )
 */
export function subscribeSongsAirdrops(callback: (data: SongsAirdropsResponse | null) => void, songId: string, airdropId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/airdrops/${airdropId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsAirdropsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsAirdrops at path '${`songs/${songId}/airdrops/${airdropId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsAirdrops items from collection songs/${songId}/airdrops
 
  Read Operation Details: Public read. Anyone can inspect buyer airdrop requests and outcomes.
  
 */
export async function getManySongsAirdrops(songId: string, filter: string = ""): Promise<SongsAirdropsResponse[]> {
  try {
    const results = await get(`songs/${songId}/airdrops`, { prompt: filter });
    return Array.isArray(results) ? results as SongsAirdropsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsAirdrops collection at path 'songs/${songId}/airdrops': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsAirdrops collection at songs/${songId}/airdrops
 
  Read Operation Details: Public read. Anyone can inspect buyer airdrop requests and outcomes.
  
 */
export function subscribeManySongsAirdrops(callback: (data: SongsAirdropsResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/airdrops`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsAirdropsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsAirdrops collection at path '${`songs/${songId}/airdrops`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsAirdrops items from collection songs/${songId}/airdrops
 
  Read Operation Details: Public read. Anyone can inspect buyer airdrop requests and outcomes.
  
 */
export async function getAllSongsAirdrops(songId: string, filter: string = ""): Promise<SongsAirdropsResponse[]> {
  try {
    const results = await get(`songs/*/airdrops`, { prompt: filter });
    return Array.isArray(results) ? results as SongsAirdropsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsAirdrops collection at path 'songs/${songId}/airdrops': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsAirdrops collection at songs/${songId}/airdrops
 
  Read Operation Details: Public read. Anyone can inspect buyer airdrop requests and outcomes.
  
 */
export function subscribeAllSongsAirdrops(callback: (data: SongsAirdropsResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/airdrops`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsAirdropsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsAirdrops collection at path '${`songs/*/airdrops`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsAirdrops items in collection songs/${songId}/airdrops.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsAirdrops(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/airdrops`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsAirdrops at path 'songs/${songId}/airdrops': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsAirdrops items in collection songs/${songId}/airdrops.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsAirdrops(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/airdrops`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsAirdrops at path 'songs/${songId}/airdrops': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Tracks which users have liked which songs. One like per user per song, with the document ID being the user's wallet address as a natural unique constraint.
 */

export interface SongsLikesRequest {
  likedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsLikesResponse {
  likedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a SongsLikes operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsLikes(songId: string, userAddress: string, data?: SongsLikesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/likes/${userAddress}`, document: doc };
}

/**
 * Users can only create a like document where the $userAddress path param matches their own wallet address, ensuring one like per user per song. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsLikes(songId: string, userAddress: string, data?: SongsLikesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/likes/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsLikes: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can see who liked a song.
   (Get Single Item)
 */
export async function getSongsLikes(songId: string, userAddress: string): Promise<SongsLikesResponse | null> {
  try {
    const result = await get(`songs/${songId}/likes/${userAddress}`);
    return result as SongsLikesResponse | null;
  } catch (error) {
    console.error(`Error getting SongsLikes: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsLikes document. (
  Read Operation Details: Public read. Anyone can see who liked a song.
  )
 */
export function subscribeSongsLikes(callback: (data: SongsLikesResponse | null) => void, songId: string, userAddress: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/likes/${userAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsLikesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsLikes at path '${`songs/${songId}/likes/${userAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsLikes items from collection songs/${songId}/likes
 
  Read Operation Details: Public read. Anyone can see who liked a song.
  
 */
export async function getManySongsLikes(songId: string, filter: string = ""): Promise<SongsLikesResponse[]> {
  try {
    const results = await get(`songs/${songId}/likes`, { prompt: filter });
    return Array.isArray(results) ? results as SongsLikesResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsLikes collection at path 'songs/${songId}/likes': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsLikes collection at songs/${songId}/likes
 
  Read Operation Details: Public read. Anyone can see who liked a song.
  
 */
export function subscribeManySongsLikes(callback: (data: SongsLikesResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/likes`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsLikesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsLikes collection at path '${`songs/${songId}/likes`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsLikes items from collection songs/${songId}/likes
 
  Read Operation Details: Public read. Anyone can see who liked a song.
  
 */
export async function getAllSongsLikes(songId: string, filter: string = ""): Promise<SongsLikesResponse[]> {
  try {
    const results = await get(`songs/*/likes`, { prompt: filter });
    return Array.isArray(results) ? results as SongsLikesResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsLikes collection at path 'songs/${songId}/likes': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsLikes collection at songs/${songId}/likes
 
  Read Operation Details: Public read. Anyone can see who liked a song.
  
 */
export function subscribeAllSongsLikes(callback: (data: SongsLikesResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/likes`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsLikesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsLikes collection at path '${`songs/*/likes`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsLikes items in collection songs/${songId}/likes.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsLikes(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/likes`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsLikes at path 'songs/${songId}/likes': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsLikes items in collection songs/${songId}/likes.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsLikes(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/likes`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsLikes at path 'songs/${songId}/likes': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Users can remove their own likes (unlike).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteSongsLikes(songId: string, userAddress: string): Promise<boolean> {
  try {
    const succeeded = await set(`songs/${songId}/likes/${userAddress}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting SongsLikes: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for SongsLikes for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteSongsLikes(songId: string, userAddress: string): DocumentOperation {
  return { path: `songs/${songId}/likes/${userAddress}`, document: null };
}


/**
 * Artist SOL payout triggered by webhook. Transfers 69% of pack price from OPERATIONS_WALLET to song creator.
 */

export interface SongsPayoutsRequest {
  recipient: AddressType;
  solAmt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsPayoutsResponse {
  recipient: string;
  solAmt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsPayouts operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsPayouts(songId: string, payoutId: string, data?: SongsPayoutsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/payouts/${payoutId}`, document: doc };
}

/**
 * Only PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET can trigger payout. Called from backend webhook. The hook transfers SOL from OPERATIONS_WALLET to @newData.recipient. solAmt is in lamports. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsPayouts(songId: string, payoutId: string, data?: SongsPayoutsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/payouts/${payoutId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsPayouts: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
   (Get Single Item)
 */
export async function getSongsPayouts(songId: string, payoutId: string): Promise<SongsPayoutsResponse | null> {
  try {
    const result = await get(`songs/${songId}/payouts/${payoutId}`);
    return result as SongsPayoutsResponse | null;
  } catch (error) {
    console.error(`Error getting SongsPayouts: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsPayouts document. (
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  )
 */
export function subscribeSongsPayouts(callback: (data: SongsPayoutsResponse | null) => void, songId: string, payoutId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/payouts/${payoutId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsPayoutsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsPayouts at path '${`songs/${songId}/payouts/${payoutId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsPayouts items from collection songs/${songId}/payouts
 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  
 */
export async function getManySongsPayouts(songId: string, filter: string = ""): Promise<SongsPayoutsResponse[]> {
  try {
    const results = await get(`songs/${songId}/payouts`, { prompt: filter });
    return Array.isArray(results) ? results as SongsPayoutsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsPayouts collection at path 'songs/${songId}/payouts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsPayouts collection at songs/${songId}/payouts
 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  
 */
export function subscribeManySongsPayouts(callback: (data: SongsPayoutsResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/payouts`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsPayoutsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsPayouts collection at path '${`songs/${songId}/payouts`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsPayouts items from collection songs/${songId}/payouts
 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  
 */
export async function getAllSongsPayouts(songId: string, filter: string = ""): Promise<SongsPayoutsResponse[]> {
  try {
    const results = await get(`songs/*/payouts`, { prompt: filter });
    return Array.isArray(results) ? results as SongsPayoutsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsPayouts collection at path 'songs/${songId}/payouts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsPayouts collection at songs/${songId}/payouts
 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  
 */
export function subscribeAllSongsPayouts(callback: (data: SongsPayoutsResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/payouts`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsPayoutsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsPayouts collection at path '${`songs/*/payouts`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsPayouts items in collection songs/${songId}/payouts.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsPayouts(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/payouts`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsPayouts at path 'songs/${songId}/payouts': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsPayouts items in collection songs/${songId}/payouts.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsPayouts(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/payouts`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsPayouts at path 'songs/${songId}/payouts': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Infrastructure fee 10% of pack price from OPERATIONS_WALLET to infrastructure wallet.
 */

export interface SongsInfraFeesRequest {
  recipient: AddressType;
  solAmt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsInfraFeesResponse {
  recipient: string;
  solAmt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsInfraFees operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsInfraFees(songId: string, feeId: string, data?: SongsInfraFeesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/infraFees/${feeId}`, document: doc };
}

/**
 * Only PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET can trigger payout. Called from backend webhook. The hook transfers SOL from OPERATIONS_WALLET to @newData.recipient. solAmt is in lamports. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsInfraFees(songId: string, feeId: string, data?: SongsInfraFeesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/infraFees/${feeId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsInfraFees: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
   (Get Single Item)
 */
export async function getSongsInfraFees(songId: string, feeId: string): Promise<SongsInfraFeesResponse | null> {
  try {
    const result = await get(`songs/${songId}/infraFees/${feeId}`);
    return result as SongsInfraFeesResponse | null;
  } catch (error) {
    console.error(`Error getting SongsInfraFees: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsInfraFees document. (
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  )
 */
export function subscribeSongsInfraFees(callback: (data: SongsInfraFeesResponse | null) => void, songId: string, feeId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/infraFees/${feeId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsInfraFeesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsInfraFees at path '${`songs/${songId}/infraFees/${feeId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsInfraFees items from collection songs/${songId}/infraFees
 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  
 */
export async function getManySongsInfraFees(songId: string, filter: string = ""): Promise<SongsInfraFeesResponse[]> {
  try {
    const results = await get(`songs/${songId}/infraFees`, { prompt: filter });
    return Array.isArray(results) ? results as SongsInfraFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsInfraFees collection at path 'songs/${songId}/infraFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsInfraFees collection at songs/${songId}/infraFees
 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  
 */
export function subscribeManySongsInfraFees(callback: (data: SongsInfraFeesResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/infraFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsInfraFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsInfraFees collection at path '${`songs/${songId}/infraFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsInfraFees items from collection songs/${songId}/infraFees
 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  
 */
export async function getAllSongsInfraFees(songId: string, filter: string = ""): Promise<SongsInfraFeesResponse[]> {
  try {
    const results = await get(`songs/*/infraFees`, { prompt: filter });
    return Array.isArray(results) ? results as SongsInfraFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsInfraFees collection at path 'songs/${songId}/infraFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsInfraFees collection at songs/${songId}/infraFees
 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  
 */
export function subscribeAllSongsInfraFees(callback: (data: SongsInfraFeesResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/infraFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsInfraFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsInfraFees collection at path '${`songs/*/infraFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsInfraFees items in collection songs/${songId}/infraFees.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsInfraFees(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/infraFees`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsInfraFees at path 'songs/${songId}/infraFees': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsInfraFees items in collection songs/${songId}/infraFees.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsInfraFees(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/infraFees`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsInfraFees at path 'songs/${songId}/infraFees': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Treasury fee 1% of pack price from OPERATIONS_WALLET to treasury wallet.
 */

export interface SongsTreasuryFeesRequest {
  recipient: AddressType;
  solAmt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsTreasuryFeesResponse {
  recipient: string;
  solAmt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsTreasuryFees operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsTreasuryFees(songId: string, feeId: string, data?: SongsTreasuryFeesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/treasuryFees/${feeId}`, document: doc };
}

/**
 * Only PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET can trigger payout. Called from backend webhook. The hook transfers SOL from OPERATIONS_WALLET to @newData.recipient. solAmt is in lamports. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsTreasuryFees(songId: string, feeId: string, data?: SongsTreasuryFeesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/treasuryFees/${feeId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsTreasuryFees: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
   (Get Single Item)
 */
export async function getSongsTreasuryFees(songId: string, feeId: string): Promise<SongsTreasuryFeesResponse | null> {
  try {
    const result = await get(`songs/${songId}/treasuryFees/${feeId}`);
    return result as SongsTreasuryFeesResponse | null;
  } catch (error) {
    console.error(`Error getting SongsTreasuryFees: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsTreasuryFees document. (
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  )
 */
export function subscribeSongsTreasuryFees(callback: (data: SongsTreasuryFeesResponse | null) => void, songId: string, feeId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/treasuryFees/${feeId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsTreasuryFeesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsTreasuryFees at path '${`songs/${songId}/treasuryFees/${feeId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsTreasuryFees items from collection songs/${songId}/treasuryFees
 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  
 */
export async function getManySongsTreasuryFees(songId: string, filter: string = ""): Promise<SongsTreasuryFeesResponse[]> {
  try {
    const results = await get(`songs/${songId}/treasuryFees`, { prompt: filter });
    return Array.isArray(results) ? results as SongsTreasuryFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsTreasuryFees collection at path 'songs/${songId}/treasuryFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsTreasuryFees collection at songs/${songId}/treasuryFees
 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  
 */
export function subscribeManySongsTreasuryFees(callback: (data: SongsTreasuryFeesResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/treasuryFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsTreasuryFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsTreasuryFees collection at path '${`songs/${songId}/treasuryFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsTreasuryFees items from collection songs/${songId}/treasuryFees
 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  
 */
export async function getAllSongsTreasuryFees(songId: string, filter: string = ""): Promise<SongsTreasuryFeesResponse[]> {
  try {
    const results = await get(`songs/*/treasuryFees`, { prompt: filter });
    return Array.isArray(results) ? results as SongsTreasuryFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsTreasuryFees collection at path 'songs/${songId}/treasuryFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsTreasuryFees collection at songs/${songId}/treasuryFees
 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  
 */
export function subscribeAllSongsTreasuryFees(callback: (data: SongsTreasuryFeesResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/treasuryFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsTreasuryFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsTreasuryFees collection at path '${`songs/*/treasuryFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsTreasuryFees items in collection songs/${songId}/treasuryFees.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsTreasuryFees(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/treasuryFees`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsTreasuryFees at path 'songs/${songId}/treasuryFees': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsTreasuryFees items in collection songs/${songId}/treasuryFees.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsTreasuryFees(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/treasuryFees`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsTreasuryFees at path 'songs/${songId}/treasuryFees': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Buy song tokens with USDC via Jupiter aggregator, with USDC platform fee.
 */

export interface SongsUsdcBuysRequest {
  usdcAmt: number | TimeOperation | IncrementOperation | TokenAmount;
  slip: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsUsdcBuysResponse {
  usdcAmt: number;
  slip: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsUsdcBuys operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsUsdcBuys(songId: string, buyId: string, data?: SongsUsdcBuysRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/usdcBuys/${buyId}`, document: doc };
}

/**
 * Any user can buy song tokens with USDC when PLATFORM_PAUSED is false and the song's paused field is not true. usdcAmt is in micro-USDC (1 USDC = 1000000). slip is slippage in basis points (500 = 5%). Uses DeFiPlugin.swap to route USDC through Jupiter for token purchase. A 2% platform fee (PLATFORM_FEE_BPS / 10000) in USDC is automatically transferred from the buyer to PROJECT_VAULT_ADDRESS. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsUsdcBuys(songId: string, buyId: string, data?: SongsUsdcBuysRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/usdcBuys/${buyId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsUsdcBuys: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read.
   (Get Single Item)
 */
export async function getSongsUsdcBuys(songId: string, buyId: string): Promise<SongsUsdcBuysResponse | null> {
  try {
    const result = await get(`songs/${songId}/usdcBuys/${buyId}`);
    return result as SongsUsdcBuysResponse | null;
  } catch (error) {
    console.error(`Error getting SongsUsdcBuys: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsUsdcBuys document. (
  Read Operation Details: Public read.
  )
 */
export function subscribeSongsUsdcBuys(callback: (data: SongsUsdcBuysResponse | null) => void, songId: string, buyId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/usdcBuys/${buyId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsUsdcBuysResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsUsdcBuys at path '${`songs/${songId}/usdcBuys/${buyId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsUsdcBuys items from collection songs/${songId}/usdcBuys
 
  Read Operation Details: Public read.
  
 */
export async function getManySongsUsdcBuys(songId: string, filter: string = ""): Promise<SongsUsdcBuysResponse[]> {
  try {
    const results = await get(`songs/${songId}/usdcBuys`, { prompt: filter });
    return Array.isArray(results) ? results as SongsUsdcBuysResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsUsdcBuys collection at path 'songs/${songId}/usdcBuys': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsUsdcBuys collection at songs/${songId}/usdcBuys
 
  Read Operation Details: Public read.
  
 */
export function subscribeManySongsUsdcBuys(callback: (data: SongsUsdcBuysResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/usdcBuys`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsUsdcBuysResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsUsdcBuys collection at path '${`songs/${songId}/usdcBuys`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsUsdcBuys items from collection songs/${songId}/usdcBuys
 
  Read Operation Details: Public read.
  
 */
export async function getAllSongsUsdcBuys(songId: string, filter: string = ""): Promise<SongsUsdcBuysResponse[]> {
  try {
    const results = await get(`songs/*/usdcBuys`, { prompt: filter });
    return Array.isArray(results) ? results as SongsUsdcBuysResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsUsdcBuys collection at path 'songs/${songId}/usdcBuys': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsUsdcBuys collection at songs/${songId}/usdcBuys
 
  Read Operation Details: Public read.
  
 */
export function subscribeAllSongsUsdcBuys(callback: (data: SongsUsdcBuysResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/usdcBuys`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsUsdcBuysResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsUsdcBuys collection at path '${`songs/*/usdcBuys`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsUsdcBuys items in collection songs/${songId}/usdcBuys.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsUsdcBuys(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/usdcBuys`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsUsdcBuys at path 'songs/${songId}/usdcBuys': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsUsdcBuys items in collection songs/${songId}/usdcBuys.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsUsdcBuys(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/usdcBuys`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsUsdcBuys at path 'songs/${songId}/usdcBuys': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Sell song tokens for USDC via Jupiter aggregator, with USDC platform fee.
 */

export interface SongsUsdcSellsRequest {
  tokenAmt: number | TimeOperation | IncrementOperation | TokenAmount;
  slip: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongsUsdcSellsResponse {
  tokenAmt: number;
  slip: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SongsUsdcSells operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongsUsdcSells(songId: string, sellId: string, data?: SongsUsdcSellsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `songs/${songId}/usdcSells/${sellId}`, document: doc };
}

/**
 * Any user can sell song tokens for USDC when PLATFORM_PAUSED is false and the song's paused field is not true. tokenAmt is the number of song tokens to sell (in base units with 6 decimals). slip is slippage in basis points (500 = 5%). Uses DeFiPlugin.swap to route tokens through Jupiter for USDC. A 2% platform fee (PLATFORM_FEE_BPS / 10000) in USDC is automatically transferred from the seller to PROJECT_VAULT_ADDRESS. The fee is calculated on the expected USD value of the tokens sold, determined by @DeFiPlugin.getSwapQuote at execution time, using @MathPlugin.mulDivFloor for overflow-safe precision. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongsUsdcSells(songId: string, sellId: string, data?: SongsUsdcSellsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`songs/${songId}/usdcSells/${sellId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongsUsdcSells: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read.
   (Get Single Item)
 */
export async function getSongsUsdcSells(songId: string, sellId: string): Promise<SongsUsdcSellsResponse | null> {
  try {
    const result = await get(`songs/${songId}/usdcSells/${sellId}`);
    return result as SongsUsdcSellsResponse | null;
  } catch (error) {
    console.error(`Error getting SongsUsdcSells: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongsUsdcSells document. (
  Read Operation Details: Public read.
  )
 */
export function subscribeSongsUsdcSells(callback: (data: SongsUsdcSellsResponse | null) => void, songId: string, sellId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/usdcSells/${sellId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsUsdcSellsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongsUsdcSells at path '${`songs/${songId}/usdcSells/${sellId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongsUsdcSells items from collection songs/${songId}/usdcSells
 
  Read Operation Details: Public read.
  
 */
export async function getManySongsUsdcSells(songId: string, filter: string = ""): Promise<SongsUsdcSellsResponse[]> {
  try {
    const results = await get(`songs/${songId}/usdcSells`, { prompt: filter });
    return Array.isArray(results) ? results as SongsUsdcSellsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsUsdcSells collection at path 'songs/${songId}/usdcSells': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsUsdcSells collection at songs/${songId}/usdcSells
 
  Read Operation Details: Public read.
  
 */
export function subscribeManySongsUsdcSells(callback: (data: SongsUsdcSellsResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}/usdcSells`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsUsdcSellsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsUsdcSells collection at path '${`songs/${songId}/usdcSells`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongsUsdcSells items from collection songs/${songId}/usdcSells
 
  Read Operation Details: Public read.
  
 */
export async function getAllSongsUsdcSells(songId: string, filter: string = ""): Promise<SongsUsdcSellsResponse[]> {
  try {
    const results = await get(`songs/*/usdcSells`, { prompt: filter });
    return Array.isArray(results) ? results as SongsUsdcSellsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongsUsdcSells collection at path 'songs/${songId}/usdcSells': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongsUsdcSells collection at songs/${songId}/usdcSells
 
  Read Operation Details: Public read.
  
 */
export function subscribeAllSongsUsdcSells(callback: (data: SongsUsdcSellsResponse[]) => void, songId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`songs/*/usdcSells`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsUsdcSellsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongsUsdcSells collection at path '${`songs/*/usdcSells`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongsUsdcSells items in collection songs/${songId}/usdcSells.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongsUsdcSells(songId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`songs/${songId}/usdcSells`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongsUsdcSells at path 'songs/${songId}/usdcSells': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongsUsdcSells items in collection songs/${songId}/usdcSells.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongsUsdcSells(songId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`songs/${songId}/usdcSells`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongsUsdcSells at path 'songs/${songId}/usdcSells': ${formatError(error)}`);
    return { value: 0 };
  }
}

