// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.119Z
// Collection: userTokenLots/$userAddress/lots/$lotId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks each token acquisition as a tax lot for per-user cost basis tracking. Created by frontend after successful buys/swaps/airdrops/pack purchases.
 */

export interface UserTokenLotsLotsRequest {
  tokenMint: AddressType;
  songId: string;
  songName: string;
  songSymbol: string;
  quantity: number | TimeOperation | IncrementOperation | TokenAmount;
  remainingQuantity: number | TimeOperation | IncrementOperation | TokenAmount;
  costBasisAmount: number | TimeOperation | IncrementOperation | TokenAmount;
  costBasisCurrency: string;
  acquiredAt: number | TimeOperation | IncrementOperation | TokenAmount;
  source: string;
  txSignature: string;
  pricePerToken: string;
}

export interface UserTokenLotsLotsResponse {
  tokenMint: string;
  songId: string;
  songName: string;
  songSymbol: string;
  quantity: number;
  remainingQuantity: number;
  costBasisAmount: number;
  costBasisCurrency: string;
  acquiredAt: number;
  source: string;
  txSignature: string;
  pricePerToken: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a UserTokenLotsLots operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUserTokenLotsLots(userAddress: string, lotId: string, data?: UserTokenLotsLotsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `userTokenLots/${userAddress}/lots/${lotId}`, document: doc };
}

/**
 * Authenticated users only. Caller must equal $userAddress. Frontend creates a lot after each successful token acquisition (buy, swap, airdrop, pack). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setUserTokenLotsLots(userAddress: string, lotId: string, data?: UserTokenLotsLotsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`userTokenLots/${userAddress}/lots/${lotId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting UserTokenLotsLots: ${formatError(error)}`);
    return false;
  }
}

export type UserTokenLotsLotsRequestUpdate = Partial<UserTokenLotsLotsRequest>;

/**
 * Build a UserTokenLotsLots update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateUserTokenLotsLots(userAddress: string, lotId: string, data: UserTokenLotsLotsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `userTokenLots/${userAddress}/lots/${lotId}`, document: doc };
}

/**
 * Owner only ($userAddress). Used to decrement remainingQuantity when tokens from this lot are sold. No other fields should change. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateUserTokenLotsLots(userAddress: string, lotId: string, data: UserTokenLotsLotsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`userTokenLots/${userAddress}/lots/${lotId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating UserTokenLotsLots: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read lot records. Public for portfolio transparency.
   (Get Single Item)
 */
export async function getUserTokenLotsLots(userAddress: string, lotId: string): Promise<UserTokenLotsLotsResponse | null> {
  try {
    const result = await get(`userTokenLots/${userAddress}/lots/${lotId}`);
    return result as UserTokenLotsLotsResponse | null;
  } catch (error) {
    console.error(`Error getting UserTokenLotsLots: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single UserTokenLotsLots document. (
  Read Operation Details: Anyone can read lot records. Public for portfolio transparency.
  )
 */
export function subscribeUserTokenLotsLots(callback: (data: UserTokenLotsLotsResponse | null) => void, userAddress: string, lotId: string): Promise<() => Promise<void>> {
  return subscribe(`userTokenLots/${userAddress}/lots/${lotId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as UserTokenLotsLotsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to UserTokenLotsLots at path '${`userTokenLots/${userAddress}/lots/${lotId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many UserTokenLotsLots items from collection userTokenLots/${userAddress}/lots
 
  Read Operation Details: Anyone can read lot records. Public for portfolio transparency.
  
 */
export async function getManyUserTokenLotsLots(userAddress: string, filter: string = ""): Promise<UserTokenLotsLotsResponse[]> {
  try {
    const results = await get(`userTokenLots/${userAddress}/lots`, { prompt: filter });
    return Array.isArray(results) ? results as UserTokenLotsLotsResponse[] : [];
  } catch (error) {
    console.error(`Error getting UserTokenLotsLots collection at path 'userTokenLots/${userAddress}/lots': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in UserTokenLotsLots collection at userTokenLots/${userAddress}/lots
 
  Read Operation Details: Anyone can read lot records. Public for portfolio transparency.
  
 */
export function subscribeManyUserTokenLotsLots(callback: (data: UserTokenLotsLotsResponse[]) => void, userAddress: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`userTokenLots/${userAddress}/lots`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UserTokenLotsLotsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to UserTokenLotsLots collection at path '${`userTokenLots/${userAddress}/lots`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all UserTokenLotsLots items from collection userTokenLots/${userAddress}/lots
 
  Read Operation Details: Anyone can read lot records. Public for portfolio transparency.
  
 */
export async function getAllUserTokenLotsLots(userAddress: string, filter: string = ""): Promise<UserTokenLotsLotsResponse[]> {
  try {
    const results = await get(`userTokenLots/*/lots`, { prompt: filter });
    return Array.isArray(results) ? results as UserTokenLotsLotsResponse[] : [];
  } catch (error) {
    console.error(`Error getting UserTokenLotsLots collection at path 'userTokenLots/${userAddress}/lots': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in UserTokenLotsLots collection at userTokenLots/${userAddress}/lots
 
  Read Operation Details: Anyone can read lot records. Public for portfolio transparency.
  
 */
export function subscribeAllUserTokenLotsLots(callback: (data: UserTokenLotsLotsResponse[]) => void, userAddress: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`userTokenLots/*/lots`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UserTokenLotsLotsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to UserTokenLotsLots collection at path '${`userTokenLots/*/lots`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count UserTokenLotsLots items in collection userTokenLots/${userAddress}/lots.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countUserTokenLotsLots(userAddress: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`userTokenLots/${userAddress}/lots`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting UserTokenLotsLots at path 'userTokenLots/${userAddress}/lots': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on UserTokenLotsLots items in collection userTokenLots/${userAddress}/lots.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateUserTokenLotsLots(userAddress: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`userTokenLots/${userAddress}/lots`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating UserTokenLotsLots at path 'userTokenLots/${userAddress}/lots': ${formatError(error)}`);
    return { value: 0 };
  }
}

