// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.119Z
// Collection: userTokenTransfers/$transferId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Onchain user-initiated SPL token transfers (USDC, song tokens, etc.). Minimal onchain collection that triggers a real SPL token movement from the user's wallet to a recipient via TokenPlugin hook.
 */

export interface UserTokenTransfersRequest {
  toAddress: AddressType;
  mintAddress: AddressType;
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface UserTokenTransfersResponse {
  toAddress: string;
  mintAddress: string;
  amount: number;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a UserTokenTransfers operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUserTokenTransfers(transferId: string, data?: UserTokenTransfersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `userTokenTransfers/${transferId}`, document: doc };
}

/**
 * Authenticated users only. Transfers SPL tokens from the caller's wallet to the specified toAddress. Amount must be provided in the token's base units. Hook executes the actual onchain token transfer via TokenPlugin. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setUserTokenTransfers(transferId: string, data?: UserTokenTransfersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`userTokenTransfers/${transferId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting UserTokenTransfers: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Publicly readable onchain transfer record. Anyone can verify the token transfer.
   (Get Single Item)
 */
export async function getUserTokenTransfers(transferId: string): Promise<UserTokenTransfersResponse | null> {
  try {
    const result = await get(`userTokenTransfers/${transferId}`);
    return result as UserTokenTransfersResponse | null;
  } catch (error) {
    console.error(`Error getting UserTokenTransfers: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single UserTokenTransfers document. (
  Read Operation Details: Publicly readable onchain transfer record. Anyone can verify the token transfer.
  )
 */
export function subscribeUserTokenTransfers(callback: (data: UserTokenTransfersResponse | null) => void, transferId: string): Promise<() => Promise<void>> {
  return subscribe(`userTokenTransfers/${transferId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as UserTokenTransfersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to UserTokenTransfers at path '${`userTokenTransfers/${transferId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many UserTokenTransfers items from collection userTokenTransfers
 
  Read Operation Details: Publicly readable onchain transfer record. Anyone can verify the token transfer.
  
 */
export async function getManyUserTokenTransfers(filter: string = ""): Promise<UserTokenTransfersResponse[]> {
  try {
    const results = await get("userTokenTransfers", { prompt: filter });
    return Array.isArray(results) ? results as UserTokenTransfersResponse[] : [];
  } catch (error) {
    console.error(`Error getting UserTokenTransfers collection at path 'userTokenTransfers': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in UserTokenTransfers collection at userTokenTransfers
 
  Read Operation Details: Publicly readable onchain transfer record. Anyone can verify the token transfer.
  
 */
export function subscribeManyUserTokenTransfers(callback: (data: UserTokenTransfersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("userTokenTransfers", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UserTokenTransfersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to UserTokenTransfers collection at path '${"userTokenTransfers"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all UserTokenTransfers items from collection userTokenTransfers
 
  Read Operation Details: Publicly readable onchain transfer record. Anyone can verify the token transfer.
  
 */
export async function getAllUserTokenTransfers(filter: string = ""): Promise<UserTokenTransfersResponse[]> {
  try {
    const results = await get("userTokenTransfers", { prompt: filter });
    return Array.isArray(results) ? results as UserTokenTransfersResponse[] : [];
  } catch (error) {
    console.error(`Error getting UserTokenTransfers collection at path 'userTokenTransfers': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in UserTokenTransfers collection at userTokenTransfers
 
  Read Operation Details: Publicly readable onchain transfer record. Anyone can verify the token transfer.
  
 */
export function subscribeAllUserTokenTransfers(callback: (data: UserTokenTransfersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("userTokenTransfers", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UserTokenTransfersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to UserTokenTransfers collection at path '${"userTokenTransfers"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count UserTokenTransfers items in collection userTokenTransfers.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countUserTokenTransfers(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("userTokenTransfers", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting UserTokenTransfers at path 'userTokenTransfers': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on UserTokenTransfers items in collection userTokenTransfers.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateUserTokenTransfers(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("userTokenTransfers", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating UserTokenTransfers at path 'userTokenTransfers': ${formatError(error)}`);
    return { value: 0 };
  }
}

