// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.119Z
// Collection: webhookFailures/$failureId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Offchain audit log for webhook verification failures (HMAC, signature, parse errors). Backend-only writes; admin-only reads. Used to surface silent failures in an admin UI and to drive Discord alerts when failure clusters are detected.
 */

export interface WebhookFailuresRequest {
  webhookSource: string;
  path: string;
  failureReason: string;
  errorMessage: string;
  headers: string;
  bodyPreview: string;
  timestamp: number | IncrementOperation | TokenAmount;
  alertSent: boolean;
}

export interface WebhookFailuresResponse {
  webhookSource: string;
  path: string;
  failureReason: string;
  errorMessage: string;
  headers: string;
  bodyPreview: string;
  timestamp: number;
  alertSent: boolean;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a WebhookFailures operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildWebhookFailures(failureId: string, data: WebhookFailuresRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `webhookFailures/${failureId}`, document: doc };
}

/**
 * Backend (@constants.PROJECT_VAULT_ADDRESS) and admin (@constants.ADMIN_ADDRESS) only. Backend writes after a webhook (Shopify, Stripe, etc.) fails HMAC/signature/processing verification. Callers must truncate errorMessage and bodyPreview and must NOT include secrets in headers. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setWebhookFailures(failureId: string, data: WebhookFailuresRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`webhookFailures/${failureId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting WebhookFailures: ${formatError(error)}`);
    return false;
  }
}

export type WebhookFailuresRequestUpdate = Partial<WebhookFailuresRequest>;

/**
 * Build a WebhookFailures update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateWebhookFailures(failureId: string, data: WebhookFailuresRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `webhookFailures/${failureId}`, document: doc };
}

/**
 * Backend (@constants.PROJECT_VAULT_ADDRESS) and admin (@constants.ADMIN_ADDRESS) only. Backend updates alertSent to true once Discord notified. Admin may resolve records during cleanup. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateWebhookFailures(failureId: string, data: WebhookFailuresRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`webhookFailures/${failureId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating WebhookFailures: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Admin (@constants.ADMIN_ADDRESS) and backend (@constants.PROJECT_VAULT_ADDRESS) only. Admin reads in admin UI to display failures; backend reads to count recent unalerted failures for Discord alert threshold detection. Regular users cannot read these internal failure logs.
   (Get Single Item)
 */
export async function getWebhookFailures(failureId: string): Promise<WebhookFailuresResponse | null> {
  try {
    const result = await get(`webhookFailures/${failureId}`);
    return result as WebhookFailuresResponse | null;
  } catch (error) {
    console.error(`Error getting WebhookFailures: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single WebhookFailures document. (
  Read Operation Details: Admin (@constants.ADMIN_ADDRESS) and backend (@constants.PROJECT_VAULT_ADDRESS) only. Admin reads in admin UI to display failures; backend reads to count recent unalerted failures for Discord alert threshold detection. Regular users cannot read these internal failure logs.
  )
 */
export function subscribeWebhookFailures(callback: (data: WebhookFailuresResponse | null) => void, failureId: string): Promise<() => Promise<void>> {
  return subscribe(`webhookFailures/${failureId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as WebhookFailuresResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to WebhookFailures at path '${`webhookFailures/${failureId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many WebhookFailures items from collection webhookFailures
 
  Read Operation Details: Admin (@constants.ADMIN_ADDRESS) and backend (@constants.PROJECT_VAULT_ADDRESS) only. Admin reads in admin UI to display failures; backend reads to count recent unalerted failures for Discord alert threshold detection. Regular users cannot read these internal failure logs.
  
 */
export async function getManyWebhookFailures(filter: string = ""): Promise<WebhookFailuresResponse[]> {
  try {
    const results = await get("webhookFailures", { prompt: filter });
    return Array.isArray(results) ? results as WebhookFailuresResponse[] : [];
  } catch (error) {
    console.error(`Error getting WebhookFailures collection at path 'webhookFailures': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in WebhookFailures collection at webhookFailures
 
  Read Operation Details: Admin (@constants.ADMIN_ADDRESS) and backend (@constants.PROJECT_VAULT_ADDRESS) only. Admin reads in admin UI to display failures; backend reads to count recent unalerted failures for Discord alert threshold detection. Regular users cannot read these internal failure logs.
  
 */
export function subscribeManyWebhookFailures(callback: (data: WebhookFailuresResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("webhookFailures", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as WebhookFailuresResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to WebhookFailures collection at path '${"webhookFailures"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all WebhookFailures items from collection webhookFailures
 
  Read Operation Details: Admin (@constants.ADMIN_ADDRESS) and backend (@constants.PROJECT_VAULT_ADDRESS) only. Admin reads in admin UI to display failures; backend reads to count recent unalerted failures for Discord alert threshold detection. Regular users cannot read these internal failure logs.
  
 */
export async function getAllWebhookFailures(filter: string = ""): Promise<WebhookFailuresResponse[]> {
  try {
    const results = await get("webhookFailures", { prompt: filter });
    return Array.isArray(results) ? results as WebhookFailuresResponse[] : [];
  } catch (error) {
    console.error(`Error getting WebhookFailures collection at path 'webhookFailures': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in WebhookFailures collection at webhookFailures
 
  Read Operation Details: Admin (@constants.ADMIN_ADDRESS) and backend (@constants.PROJECT_VAULT_ADDRESS) only. Admin reads in admin UI to display failures; backend reads to count recent unalerted failures for Discord alert threshold detection. Regular users cannot read these internal failure logs.
  
 */
export function subscribeAllWebhookFailures(callback: (data: WebhookFailuresResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("webhookFailures", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as WebhookFailuresResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to WebhookFailures collection at path '${"webhookFailures"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Admin (@constants.ADMIN_ADDRESS) only. Used for cleanup/debugging of resolved failures. Regular users and backend cannot delete records.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteWebhookFailures(failureId: string): Promise<boolean> {
  try {
    const succeeded = await set(`webhookFailures/${failureId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting WebhookFailures: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for WebhookFailures for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteWebhookFailures(failureId: string): DocumentOperation {
  return { path: `webhookFailures/${failureId}`, document: null };
}

