// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: albums/$albumId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Album token collection. Each album is launched as a tradable SPL token via PumpFunPlugin with automatic bonding curve, mirroring the songs pattern. Albums act as containers/access tokens for a curated set of songs that may be private until graduated to public.
 */

export interface AlbumsRequest {
  name: string;
  symbol: string;
  uri: string;
  creator: AddressType;
  coverArtUrl?: string;
  slotCount: number | TimeOperation | IncrementOperation | TokenAmount;
  description?: string;
}

export interface AlbumsResponse {
  name: string;
  symbol: string;
  uri: string;
  creator: string;
  coverArtUrl?: string;
  slotCount: number;
  description?: string;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a Albums operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildAlbums(albumId: string, data?: AlbumsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `albums/${albumId}`, document: doc };
}

/**
 * Authenticated artists can create their own album token when creator matches their wallet. ADMIN_ADDRESS and PROJECT_VAULT_ADDRESS can also create albums for bootstrap or seed data. The uri field must be a Metaplex-standard JSON metadata URL; the PumpFunPlugin hook launches the album token on Pump.fun with automatic bonding curve. slotCount defines how many song slots the album will hold (e.g., 8 or 12). Use getTokenMintAddress to retrieve the resulting mint. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setAlbums(albumId: string, data?: AlbumsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`albums/${albumId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Albums: ${formatError(error)}`);
    return false;
  }
}

export type AlbumsRequestUpdate = Partial<AlbumsRequest>;

/**
 * Build a Albums update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateAlbums(albumId: string, data: AlbumsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `albums/${albumId}`, document: doc };
}

/**
 * Creator (artist), PROJECT_VAULT_ADDRESS, or ADMIN_ADDRESS can update mutable metadata fields like coverArtUrl, description, and slotCount. Token-defining fields (name/symbol/uri/creator) are readonly. No on-chain hook on update. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateAlbums(albumId: string, data: AlbumsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`albums/${albumId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Albums: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can view album token data, bonding curve progress, creator fees, and token balances via queries.
   (Get Single Item)
 */
export async function getAlbums(albumId: string): Promise<AlbumsResponse | null> {
  try {
    const result = await get(`albums/${albumId}`);
    return result as AlbumsResponse | null;
  } catch (error) {
    console.error(`Error getting Albums: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Albums document. (
  Read Operation Details: Public read. Anyone can view album token data, bonding curve progress, creator fees, and token balances via queries.
  )
 */
export function subscribeAlbums(callback: (data: AlbumsResponse | null) => void, albumId: string): Promise<() => Promise<void>> {
  return subscribe(`albums/${albumId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as AlbumsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Albums at path '${`albums/${albumId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Albums items from collection albums
 
  Read Operation Details: Public read. Anyone can view album token data, bonding curve progress, creator fees, and token balances via queries.
  
 */
export async function getManyAlbums(filter: string = ""): Promise<AlbumsResponse[]> {
  try {
    const results = await get("albums", { prompt: filter });
    return Array.isArray(results) ? results as AlbumsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Albums collection at path 'albums': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Albums collection at albums
 
  Read Operation Details: Public read. Anyone can view album token data, bonding curve progress, creator fees, and token balances via queries.
  
 */
export function subscribeManyAlbums(callback: (data: AlbumsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("albums", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AlbumsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Albums collection at path '${"albums"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Albums items from collection albums
 
  Read Operation Details: Public read. Anyone can view album token data, bonding curve progress, creator fees, and token balances via queries.
  
 */
export async function getAllAlbums(filter: string = ""): Promise<AlbumsResponse[]> {
  try {
    const results = await get("albums", { prompt: filter });
    return Array.isArray(results) ? results as AlbumsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Albums collection at path 'albums': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Albums collection at albums
 
  Read Operation Details: Public read. Anyone can view album token data, bonding curve progress, creator fees, and token balances via queries.
  
 */
export function subscribeAllAlbums(callback: (data: AlbumsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("albums", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as AlbumsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Albums collection at path '${"albums"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Albums items in collection albums.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countAlbums(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("albums", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Albums at path 'albums': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Albums items in collection albums.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateAlbums(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("albums", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Albums at path 'albums': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getTokenMintAddress" query on Albums.
 * Query Logic: @TokenPlugin.getTokenMintAddress($albumId, @data.name, @data.symbol)
 */
export async function runGetTokenMintAddressQueryForAlbums(albumId: string, ): Promise<string> {
  try {
    const result = await runQuery(`albums/${albumId}`, "getTokenMintAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getTokenMintAddress" on Albums: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getBondingCurveProgress" query on Albums.
 * Query Logic: @PumpFunPlugin.getBondingCurveProgress(@TokenPlugin.getTokenMintAddress($albumId, @data.name, @data.symbol))
 */
export async function runGetBondingCurveProgressQueryForAlbums(albumId: string, ): Promise<number> {
  try {
    const result = await runQuery(`albums/${albumId}`, "getBondingCurveProgress", {});
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getBondingCurveProgress" on Albums: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getCreatorFee" query on Albums.
 * Query Logic: @PumpFunPlugin.getCreatorFee(@TokenPlugin.getTokenMintAddress($albumId, @data.name, @data.symbol))
 */
export async function runGetCreatorFeeQueryForAlbums(albumId: string, ): Promise<number> {
  try {
    const result = await runQuery(`albums/${albumId}`, "getCreatorFee", {});
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getCreatorFee" on Albums: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "getTokenBalance" query on Albums. */
interface AlbumsGetTokenBalanceArgs {
  walletAddress: string;
}

/**
 * Runs the "getTokenBalance" query on Albums.
 * Query Logic: @TokenPlugin.getBalance(@newData.walletAddress, @TokenPlugin.getTokenMintAddress($albumId, @data.name, @data.symbol))
 */
export async function runGetTokenBalanceQueryForAlbums(albumId: string, args: AlbumsGetTokenBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`albums/${albumId}`, "getTokenBalance", args);
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getTokenBalance" on Albums: ${formatError(error)}`);
    throw error;
  }
}

