// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: applePayDailyBudget/$date
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Daily Apple Pay spending tracker to enforce a $300/day cap. One record per calendar day, keyed by ISO date string.
 */

export interface ApplePayDailyBudgetRequest {
  date: string;
  reservedUsd: number | IncrementOperation | TokenAmount;
  fulfilledUsd: number | IncrementOperation | TokenAmount;
  reservations: string;
  updatedAt: number | IncrementOperation | TokenAmount;
}

export interface ApplePayDailyBudgetResponse {
  date: string;
  reservedUsd: number;
  fulfilledUsd: number;
  reservations: string;
  updatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a ApplePayDailyBudget operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildApplePayDailyBudget(date: string, data: ApplePayDailyBudgetRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `applePayDailyBudget/${date}`, document: doc };
}

/**
 * Backend only. PROJECT_VAULT_ADDRESS creates the day's record on first checkout of the day with initial reservedUsd=0, fulfilledUsd=0, reservations='[]'. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setApplePayDailyBudget(date: string, data: ApplePayDailyBudgetRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`applePayDailyBudget/${date}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting ApplePayDailyBudget: ${formatError(error)}`);
    return false;
  }
}

export type ApplePayDailyBudgetRequestUpdate = Partial<ApplePayDailyBudgetRequest>;

/**
 * Build a ApplePayDailyBudget update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateApplePayDailyBudget(date: string, data: ApplePayDailyBudgetRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `applePayDailyBudget/${date}`, document: doc };
}

/**
 * Backend only. PROJECT_VAULT_ADDRESS updates reservedUsd (increment on checkout creation, decrement on fulfillment/expiration) and fulfilledUsd (increment on webhook fulfillment). Also updates reservations JSON and updatedAt. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateApplePayDailyBudget(date: string, data: ApplePayDailyBudgetRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`applePayDailyBudget/${date}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating ApplePayDailyBudget: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Backend only. PROJECT_VAULT_ADDRESS reads the day's record before creating Shopify checkouts to enforce the daily spending cap.
   (Get Single Item)
 */
export async function getApplePayDailyBudget(date: string): Promise<ApplePayDailyBudgetResponse | null> {
  try {
    const result = await get(`applePayDailyBudget/${date}`);
    return result as ApplePayDailyBudgetResponse | null;
  } catch (error) {
    console.error(`Error getting ApplePayDailyBudget: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single ApplePayDailyBudget document. (
  Read Operation Details: Backend only. PROJECT_VAULT_ADDRESS reads the day's record before creating Shopify checkouts to enforce the daily spending cap.
  )
 */
export function subscribeApplePayDailyBudget(callback: (data: ApplePayDailyBudgetResponse | null) => void, date: string): Promise<() => Promise<void>> {
  return subscribe(`applePayDailyBudget/${date}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ApplePayDailyBudgetResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to ApplePayDailyBudget at path '${`applePayDailyBudget/${date}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many ApplePayDailyBudget items from collection applePayDailyBudget
 
  Read Operation Details: Backend only. PROJECT_VAULT_ADDRESS reads the day's record before creating Shopify checkouts to enforce the daily spending cap.
  
 */
export async function getManyApplePayDailyBudget(filter: string = ""): Promise<ApplePayDailyBudgetResponse[]> {
  try {
    const results = await get("applePayDailyBudget", { prompt: filter });
    return Array.isArray(results) ? results as ApplePayDailyBudgetResponse[] : [];
  } catch (error) {
    console.error(`Error getting ApplePayDailyBudget collection at path 'applePayDailyBudget': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in ApplePayDailyBudget collection at applePayDailyBudget
 
  Read Operation Details: Backend only. PROJECT_VAULT_ADDRESS reads the day's record before creating Shopify checkouts to enforce the daily spending cap.
  
 */
export function subscribeManyApplePayDailyBudget(callback: (data: ApplePayDailyBudgetResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("applePayDailyBudget", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ApplePayDailyBudgetResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to ApplePayDailyBudget collection at path '${"applePayDailyBudget"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all ApplePayDailyBudget items from collection applePayDailyBudget
 
  Read Operation Details: Backend only. PROJECT_VAULT_ADDRESS reads the day's record before creating Shopify checkouts to enforce the daily spending cap.
  
 */
export async function getAllApplePayDailyBudget(filter: string = ""): Promise<ApplePayDailyBudgetResponse[]> {
  try {
    const results = await get("applePayDailyBudget", { prompt: filter });
    return Array.isArray(results) ? results as ApplePayDailyBudgetResponse[] : [];
  } catch (error) {
    console.error(`Error getting ApplePayDailyBudget collection at path 'applePayDailyBudget': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in ApplePayDailyBudget collection at applePayDailyBudget
 
  Read Operation Details: Backend only. PROJECT_VAULT_ADDRESS reads the day's record before creating Shopify checkouts to enforce the daily spending cap.
  
 */
export function subscribeAllApplePayDailyBudget(callback: (data: ApplePayDailyBudgetResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("applePayDailyBudget", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ApplePayDailyBudgetResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to ApplePayDailyBudget collection at path '${"applePayDailyBudget"}': ${formatError(error)}`);
    }
  });
}

