// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.094Z
// Collection: chatReactions/$reactionId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Individual reaction records for chat messages. Document ID should be a composite like {messageId}_{walletAddress}_{emoji} using underscores for natural uniqueness (one reaction per user per emoji per message).
 */

export interface ChatReactionsRequest {
  messageId: string;
  walletAddress: AddressType;
  emoji: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface ChatReactionsResponse {
  messageId: string;
  walletAddress: string;
  emoji: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a ChatReactions operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildChatReactions(reactionId: string, data?: ChatReactionsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `chatReactions/${reactionId}`, document: doc };
}

/**
 * Authenticated users can react to messages. walletAddress must match caller to prevent spoofing. Document ID should be composite {messageId}_{walletAddress}_{emoji} using underscores (not hyphens) for natural dedup. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setChatReactions(reactionId: string, data?: ChatReactionsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`chatReactions/${reactionId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting ChatReactions: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can view message reactions and counts.
   (Get Single Item)
 */
export async function getChatReactions(reactionId: string): Promise<ChatReactionsResponse | null> {
  try {
    const result = await get(`chatReactions/${reactionId}`);
    return result as ChatReactionsResponse | null;
  } catch (error) {
    console.error(`Error getting ChatReactions: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single ChatReactions document. (
  Read Operation Details: Public read. Anyone can view message reactions and counts.
  )
 */
export function subscribeChatReactions(callback: (data: ChatReactionsResponse | null) => void, reactionId: string): Promise<() => Promise<void>> {
  return subscribe(`chatReactions/${reactionId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ChatReactionsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to ChatReactions at path '${`chatReactions/${reactionId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many ChatReactions items from collection chatReactions
 
  Read Operation Details: Public read. Anyone can view message reactions and counts.
  
 */
export async function getManyChatReactions(filter: string = ""): Promise<ChatReactionsResponse[]> {
  try {
    const results = await get("chatReactions", { prompt: filter });
    return Array.isArray(results) ? results as ChatReactionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting ChatReactions collection at path 'chatReactions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in ChatReactions collection at chatReactions
 
  Read Operation Details: Public read. Anyone can view message reactions and counts.
  
 */
export function subscribeManyChatReactions(callback: (data: ChatReactionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("chatReactions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ChatReactionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to ChatReactions collection at path '${"chatReactions"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all ChatReactions items from collection chatReactions
 
  Read Operation Details: Public read. Anyone can view message reactions and counts.
  
 */
export async function getAllChatReactions(filter: string = ""): Promise<ChatReactionsResponse[]> {
  try {
    const results = await get("chatReactions", { prompt: filter });
    return Array.isArray(results) ? results as ChatReactionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting ChatReactions collection at path 'chatReactions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in ChatReactions collection at chatReactions
 
  Read Operation Details: Public read. Anyone can view message reactions and counts.
  
 */
export function subscribeAllChatReactions(callback: (data: ChatReactionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("chatReactions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ChatReactionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to ChatReactions collection at path '${"chatReactions"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count ChatReactions items in collection chatReactions.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countChatReactions(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("chatReactions", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting ChatReactions at path 'chatReactions': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on ChatReactions items in collection chatReactions.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateChatReactions(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("chatReactions", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating ChatReactions at path 'chatReactions': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Users can remove their own reactions to toggle them off.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteChatReactions(reactionId: string): Promise<boolean> {
  try {
    const succeeded = await set(`chatReactions/${reactionId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting ChatReactions: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for ChatReactions for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteChatReactions(reactionId: string): DocumentOperation {
  return { path: `chatReactions/${reactionId}`, document: null };
}

