// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: failedFulfillments/$fulfillmentId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin retry queue for failed purchase fulfillments. Backend writes records here when ANY step (fee transfer, airdrop, or both) fails during pack/song purchase fulfillment, ensuring all-or-nothing atomicity per project policy. Admin can read, retry, and resolve entries.
 */

export interface FailedFulfillmentsRequest {
  purchaseId: string;
  purchaseSource: string;
  buyerAddress: AddressType;
  songId: string;
  packId: string;
  usdAmount: number | TimeOperation | IncrementOperation | TokenAmount;
  solAmount?: number | TimeOperation | IncrementOperation | TokenAmount;
  failureStage: string;
  failureReason: string;
  retryCount: number | TimeOperation | IncrementOperation | TokenAmount;
  lastRetryAt?: number | TimeOperation | IncrementOperation | TokenAmount;
  resolvedAt?: number | TimeOperation | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface FailedFulfillmentsResponse {
  purchaseId: string;
  purchaseSource: string;
  buyerAddress: string;
  songId: string;
  packId: string;
  usdAmount: number;
  solAmount?: number;
  failureStage: string;
  failureReason: string;
  retryCount: number;
  lastRetryAt?: number;
  resolvedAt?: number;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a FailedFulfillments operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFailedFulfillments(fulfillmentId: string, data: FailedFulfillmentsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `failedFulfillments/${fulfillmentId}`, document: doc };
}

/**
 * PROJECT_VAULT_ADDRESS (backend) only. Backend writes one record per fulfillment failure with purchaseId, buyerAddress, songId, packId, financial details, and failureStage ('fee-transfer' | 'airdrop' | 'both' | 'unknown'). purchaseId is immutable; retryCount starts at 0. createdAt is required (Unix seconds). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFailedFulfillments(fulfillmentId: string, data: FailedFulfillmentsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`failedFulfillments/${fulfillmentId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting FailedFulfillments: ${formatError(error)}`);
    return false;
  }
}

export type FailedFulfillmentsRequestUpdate = Partial<FailedFulfillmentsRequest>;

/**
 * Build a FailedFulfillments update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateFailedFulfillments(fulfillmentId: string, data: FailedFulfillmentsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `failedFulfillments/${fulfillmentId}`, document: doc };
}

/**
 * PROJECT_VAULT_ADDRESS (backend) only. Backend increments retryCount, sets lastRetryAt, and sets resolvedAt (Unix seconds) when a retry succeeds. failureStage / failureReason may be updated to reflect the most recent retry attempt. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateFailedFulfillments(fulfillmentId: string, data: FailedFulfillmentsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`failedFulfillments/${fulfillmentId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating FailedFulfillments: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Admin only. ADMIN_ADDRESS reads the failed-fulfillment queue for review and retry decisions. No other roles can read (contains sensitive purchase + failure-reason data).
   (Get Single Item)
 */
export async function getFailedFulfillments(fulfillmentId: string): Promise<FailedFulfillmentsResponse | null> {
  try {
    const result = await get(`failedFulfillments/${fulfillmentId}`);
    return result as FailedFulfillmentsResponse | null;
  } catch (error) {
    console.error(`Error getting FailedFulfillments: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single FailedFulfillments document. (
  Read Operation Details: Admin only. ADMIN_ADDRESS reads the failed-fulfillment queue for review and retry decisions. No other roles can read (contains sensitive purchase + failure-reason data).
  )
 */
export function subscribeFailedFulfillments(callback: (data: FailedFulfillmentsResponse | null) => void, fulfillmentId: string): Promise<() => Promise<void>> {
  return subscribe(`failedFulfillments/${fulfillmentId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FailedFulfillmentsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to FailedFulfillments at path '${`failedFulfillments/${fulfillmentId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many FailedFulfillments items from collection failedFulfillments
 
  Read Operation Details: Admin only. ADMIN_ADDRESS reads the failed-fulfillment queue for review and retry decisions. No other roles can read (contains sensitive purchase + failure-reason data).
  
 */
export async function getManyFailedFulfillments(filter: string = ""): Promise<FailedFulfillmentsResponse[]> {
  try {
    const results = await get("failedFulfillments", { prompt: filter });
    return Array.isArray(results) ? results as FailedFulfillmentsResponse[] : [];
  } catch (error) {
    console.error(`Error getting FailedFulfillments collection at path 'failedFulfillments': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FailedFulfillments collection at failedFulfillments
 
  Read Operation Details: Admin only. ADMIN_ADDRESS reads the failed-fulfillment queue for review and retry decisions. No other roles can read (contains sensitive purchase + failure-reason data).
  
 */
export function subscribeManyFailedFulfillments(callback: (data: FailedFulfillmentsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("failedFulfillments", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FailedFulfillmentsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FailedFulfillments collection at path '${"failedFulfillments"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all FailedFulfillments items from collection failedFulfillments
 
  Read Operation Details: Admin only. ADMIN_ADDRESS reads the failed-fulfillment queue for review and retry decisions. No other roles can read (contains sensitive purchase + failure-reason data).
  
 */
export async function getAllFailedFulfillments(filter: string = ""): Promise<FailedFulfillmentsResponse[]> {
  try {
    const results = await get("failedFulfillments", { prompt: filter });
    return Array.isArray(results) ? results as FailedFulfillmentsResponse[] : [];
  } catch (error) {
    console.error(`Error getting FailedFulfillments collection at path 'failedFulfillments': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FailedFulfillments collection at failedFulfillments
 
  Read Operation Details: Admin only. ADMIN_ADDRESS reads the failed-fulfillment queue for review and retry decisions. No other roles can read (contains sensitive purchase + failure-reason data).
  
 */
export function subscribeAllFailedFulfillments(callback: (data: FailedFulfillmentsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("failedFulfillments", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FailedFulfillmentsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FailedFulfillments collection at path '${"failedFulfillments"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: ADMIN_ADDRESS only. Admin can clear resolved entries from the queue manually after confirming successful retry.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteFailedFulfillments(fulfillmentId: string): Promise<boolean> {
  try {
    const succeeded = await set(`failedFulfillments/${fulfillmentId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting FailedFulfillments: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for FailedFulfillments for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteFailedFulfillments(fulfillmentId: string): DocumentOperation {
  return { path: `failedFulfillments/${fulfillmentId}`, document: null };
}

