// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.094Z
// Collection: nftMints/$nftId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Metaplex NFT editions for songs. Each song can have NFT bundles or limited editions minted alongside the SPL token.
 */

export interface NftMintsRequest {
  songId: string;
  mintAddress: AddressType;
  owner: AddressType;
  tokenMint: AddressType;
  title: string;
  artist: string;
  coverImage?: string;
  isSoulbound: boolean;
  editionType: string;
  editionNumber?: number | IncrementOperation | TokenAmount;
  totalEditions?: number | IncrementOperation | TokenAmount;
  royaltyBps?: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface NftMintsResponse {
  songId: string;
  mintAddress: string;
  owner: string;
  tokenMint: string;
  title: string;
  artist: string;
  coverImage?: string;
  isSoulbound: boolean;
  editionType: string;
  editionNumber?: number;
  totalEditions?: number;
  royaltyBps?: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a NftMints operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildNftMints(nftId: string, data: NftMintsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `nftMints/${nftId}`, document: doc };
}

/**
 * Authenticated users can create a record when owner matches the caller wallet, or the backend vault (PROJECT_VAULT_ADDRESS) can create records on behalf of buyers during Shopify webhook dual-mint fulfillment. The frontend should provide the associated songId, tokenMint, title, artist, edition metadata, and the minted Metaplex mintAddress after the dual-mint flow completes. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setNftMints(nftId: string, data: NftMintsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`nftMints/${nftId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting NftMints: ${formatError(error)}`);
    return false;
  }
}

export type NftMintsRequestUpdate = Partial<NftMintsRequest>;

/**
 * Build a NftMints update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateNftMints(nftId: string, data: NftMintsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `nftMints/${nftId}`, document: doc };
}

/**
 * Only the stored owner can update mutable metadata fields for the NFT mint record. Immutable fields marked with ! such as songId, mintAddress, owner, tokenMint, title, and artist cannot be changed after creation. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateNftMints(nftId: string, data: NftMintsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`nftMints/${nftId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating NftMints: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read NFT mint records because onchain documents are public. The collection links song releases to their NFT edition mint addresses and ownership metadata.
   (Get Single Item)
 */
export async function getNftMints(nftId: string): Promise<NftMintsResponse | null> {
  try {
    const result = await get(`nftMints/${nftId}`);
    return result as NftMintsResponse | null;
  } catch (error) {
    console.error(`Error getting NftMints: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single NftMints document. (
  Read Operation Details: Anyone can read NFT mint records because onchain documents are public. The collection links song releases to their NFT edition mint addresses and ownership metadata.
  )
 */
export function subscribeNftMints(callback: (data: NftMintsResponse | null) => void, nftId: string): Promise<() => Promise<void>> {
  return subscribe(`nftMints/${nftId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as NftMintsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to NftMints at path '${`nftMints/${nftId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many NftMints items from collection nftMints
 
  Read Operation Details: Anyone can read NFT mint records because onchain documents are public. The collection links song releases to their NFT edition mint addresses and ownership metadata.
  
 */
export async function getManyNftMints(filter: string = ""): Promise<NftMintsResponse[]> {
  try {
    const results = await get("nftMints", { prompt: filter });
    return Array.isArray(results) ? results as NftMintsResponse[] : [];
  } catch (error) {
    console.error(`Error getting NftMints collection at path 'nftMints': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in NftMints collection at nftMints
 
  Read Operation Details: Anyone can read NFT mint records because onchain documents are public. The collection links song releases to their NFT edition mint addresses and ownership metadata.
  
 */
export function subscribeManyNftMints(callback: (data: NftMintsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("nftMints", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as NftMintsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to NftMints collection at path '${"nftMints"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all NftMints items from collection nftMints
 
  Read Operation Details: Anyone can read NFT mint records because onchain documents are public. The collection links song releases to their NFT edition mint addresses and ownership metadata.
  
 */
export async function getAllNftMints(filter: string = ""): Promise<NftMintsResponse[]> {
  try {
    const results = await get("nftMints", { prompt: filter });
    return Array.isArray(results) ? results as NftMintsResponse[] : [];
  } catch (error) {
    console.error(`Error getting NftMints collection at path 'nftMints': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in NftMints collection at nftMints
 
  Read Operation Details: Anyone can read NFT mint records because onchain documents are public. The collection links song releases to their NFT edition mint addresses and ownership metadata.
  
 */
export function subscribeAllNftMints(callback: (data: NftMintsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("nftMints", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as NftMintsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to NftMints collection at path '${"nftMints"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count NftMints items in collection nftMints.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countNftMints(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("nftMints", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting NftMints at path 'nftMints': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on NftMints items in collection nftMints.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateNftMints(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("nftMints", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating NftMints at path 'nftMints': ${formatError(error)}`);
    return { value: 0 };
  }
}

