// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: notifications/$notificationId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Offchain notification documents for the Lit Studio music platform. Each document represents a single notification sent to a user (recipient) about an event triggered by another user or the system (actor). Types include likes, follows, reposts, and stream milestones.
 */

export interface NotificationsRequest {
  recipientAddress: AddressType;
  type: string;
  actorAddress: string;
  actorName: string;
  referenceId: string;
  referenceTitle: string;
  message: string;
  isRead: boolean;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface NotificationsResponse {
  recipientAddress: string;
  type: string;
  actorAddress: string;
  actorName: string;
  referenceId: string;
  referenceTitle: string;
  message: string;
  isRead: boolean;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Notifications operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildNotifications(notificationId: string, data: NotificationsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `notifications/${notificationId}`, document: doc };
}

/**
 * Only the backend server (PROJECT_VAULT_ADDRESS) can create notifications. Frontend clients cannot create notifications directly; they are generated server-side in response to platform events. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setNotifications(notificationId: string, data: NotificationsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`notifications/${notificationId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Notifications: ${formatError(error)}`);
    return false;
  }
}

export type NotificationsRequestUpdate = Partial<NotificationsRequest>;

/**
 * Build a Notifications update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateNotifications(notificationId: string, data: NotificationsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `notifications/${notificationId}`, document: doc };
}

/**
 * Only the recipient can update their own notifications. The typical use case is marking isRead from false to true. No other fields should be modified by recipients. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateNotifications(notificationId: string, data: NotificationsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`notifications/${notificationId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Notifications: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Only the recipient of the notification can read it. Authenticated users querying this collection will only see notifications where their wallet address matches recipientAddress.
   (Get Single Item)
 */
export async function getNotifications(notificationId: string): Promise<NotificationsResponse | null> {
  try {
    const result = await get(`notifications/${notificationId}`);
    return result as NotificationsResponse | null;
  } catch (error) {
    console.error(`Error getting Notifications: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Notifications document. (
  Read Operation Details: Only the recipient of the notification can read it. Authenticated users querying this collection will only see notifications where their wallet address matches recipientAddress.
  )
 */
export function subscribeNotifications(callback: (data: NotificationsResponse | null) => void, notificationId: string): Promise<() => Promise<void>> {
  return subscribe(`notifications/${notificationId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as NotificationsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Notifications at path '${`notifications/${notificationId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Notifications items from collection notifications
 
  Read Operation Details: Only the recipient of the notification can read it. Authenticated users querying this collection will only see notifications where their wallet address matches recipientAddress.
  
 */
export async function getManyNotifications(filter: string = ""): Promise<NotificationsResponse[]> {
  try {
    const results = await get("notifications", { prompt: filter });
    return Array.isArray(results) ? results as NotificationsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Notifications collection at path 'notifications': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Notifications collection at notifications
 
  Read Operation Details: Only the recipient of the notification can read it. Authenticated users querying this collection will only see notifications where their wallet address matches recipientAddress.
  
 */
export function subscribeManyNotifications(callback: (data: NotificationsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("notifications", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as NotificationsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Notifications collection at path '${"notifications"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Notifications items from collection notifications
 
  Read Operation Details: Only the recipient of the notification can read it. Authenticated users querying this collection will only see notifications where their wallet address matches recipientAddress.
  
 */
export async function getAllNotifications(filter: string = ""): Promise<NotificationsResponse[]> {
  try {
    const results = await get("notifications", { prompt: filter });
    return Array.isArray(results) ? results as NotificationsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Notifications collection at path 'notifications': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Notifications collection at notifications
 
  Read Operation Details: Only the recipient of the notification can read it. Authenticated users querying this collection will only see notifications where their wallet address matches recipientAddress.
  
 */
export function subscribeAllNotifications(callback: (data: NotificationsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("notifications", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as NotificationsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Notifications collection at path '${"notifications"}': ${formatError(error)}`);
    }
  });
}

