// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.094Z
// Collection: operationsFulfillmentCosts/$costId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Audit trail for pack fulfillment costs - records estimated and actual SOL costs per order for operations wallet monitoring. Created and managed exclusively by the backend vault.
 */

export interface OperationsFulfillmentCostsRequest {
  orderId: string;
  nftCount: number | TimeOperation | IncrementOperation | TokenAmount;
  estimatedCostSOL: number | TimeOperation | IncrementOperation | TokenAmount;
  actualCostSOL?: number | TimeOperation | IncrementOperation | TokenAmount;
  timestamp: number | TimeOperation | IncrementOperation | TokenAmount;
  status: string;
}

export interface OperationsFulfillmentCostsResponse {
  orderId: string;
  nftCount: number;
  estimatedCostSOL: number;
  actualCostSOL?: number;
  timestamp: number;
  status: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a OperationsFulfillmentCosts operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildOperationsFulfillmentCosts(costId: string, data?: OperationsFulfillmentCostsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `operationsFulfillmentCosts/${costId}`, document: doc };
}

/**
 * Only the backend vault (PROJECT_VAULT_ADDRESS) or OPERATIONS_WALLET can create fulfillment cost records. orderId, nftCount, estimatedCostSOL, and timestamp are immutable. status must be 'success' or 'insufficient_funds'. actualCostSOL is optional and set post-fulfillment. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setOperationsFulfillmentCosts(costId: string, data?: OperationsFulfillmentCostsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`operationsFulfillmentCosts/${costId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting OperationsFulfillmentCosts: ${formatError(error)}`);
    return false;
  }
}

export type OperationsFulfillmentCostsRequestUpdate = Partial<OperationsFulfillmentCostsRequest>;

/**
 * Build a OperationsFulfillmentCosts update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateOperationsFulfillmentCosts(costId: string, data: OperationsFulfillmentCostsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `operationsFulfillmentCosts/${costId}`, document: doc };
}

/**
 * Only the backend vault (PROJECT_VAULT_ADDRESS) or OPERATIONS_WALLET can update records, typically to set actualCostSOL after fulfillment completes. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateOperationsFulfillmentCosts(costId: string, data: OperationsFulfillmentCostsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`operationsFulfillmentCosts/${costId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating OperationsFulfillmentCosts: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: ADMIN_ADDRESS, PROJECT_VAULT_ADDRESS, and OPERATIONS_WALLET can read fulfillment cost records for operations wallet monitoring and auditing. OPERATIONS_WALLET added for forward compatibility in case it later diverges from PROJECT_VAULT_ADDRESS.
   (Get Single Item)
 */
export async function getOperationsFulfillmentCosts(costId: string): Promise<OperationsFulfillmentCostsResponse | null> {
  try {
    const result = await get(`operationsFulfillmentCosts/${costId}`);
    return result as OperationsFulfillmentCostsResponse | null;
  } catch (error) {
    console.error(`Error getting OperationsFulfillmentCosts: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single OperationsFulfillmentCosts document. (
  Read Operation Details: ADMIN_ADDRESS, PROJECT_VAULT_ADDRESS, and OPERATIONS_WALLET can read fulfillment cost records for operations wallet monitoring and auditing. OPERATIONS_WALLET added for forward compatibility in case it later diverges from PROJECT_VAULT_ADDRESS.
  )
 */
export function subscribeOperationsFulfillmentCosts(callback: (data: OperationsFulfillmentCostsResponse | null) => void, costId: string): Promise<() => Promise<void>> {
  return subscribe(`operationsFulfillmentCosts/${costId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as OperationsFulfillmentCostsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to OperationsFulfillmentCosts at path '${`operationsFulfillmentCosts/${costId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many OperationsFulfillmentCosts items from collection operationsFulfillmentCosts
 
  Read Operation Details: ADMIN_ADDRESS, PROJECT_VAULT_ADDRESS, and OPERATIONS_WALLET can read fulfillment cost records for operations wallet monitoring and auditing. OPERATIONS_WALLET added for forward compatibility in case it later diverges from PROJECT_VAULT_ADDRESS.
  
 */
export async function getManyOperationsFulfillmentCosts(filter: string = ""): Promise<OperationsFulfillmentCostsResponse[]> {
  try {
    const results = await get("operationsFulfillmentCosts", { prompt: filter });
    return Array.isArray(results) ? results as OperationsFulfillmentCostsResponse[] : [];
  } catch (error) {
    console.error(`Error getting OperationsFulfillmentCosts collection at path 'operationsFulfillmentCosts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in OperationsFulfillmentCosts collection at operationsFulfillmentCosts
 
  Read Operation Details: ADMIN_ADDRESS, PROJECT_VAULT_ADDRESS, and OPERATIONS_WALLET can read fulfillment cost records for operations wallet monitoring and auditing. OPERATIONS_WALLET added for forward compatibility in case it later diverges from PROJECT_VAULT_ADDRESS.
  
 */
export function subscribeManyOperationsFulfillmentCosts(callback: (data: OperationsFulfillmentCostsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("operationsFulfillmentCosts", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as OperationsFulfillmentCostsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to OperationsFulfillmentCosts collection at path '${"operationsFulfillmentCosts"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all OperationsFulfillmentCosts items from collection operationsFulfillmentCosts
 
  Read Operation Details: ADMIN_ADDRESS, PROJECT_VAULT_ADDRESS, and OPERATIONS_WALLET can read fulfillment cost records for operations wallet monitoring and auditing. OPERATIONS_WALLET added for forward compatibility in case it later diverges from PROJECT_VAULT_ADDRESS.
  
 */
export async function getAllOperationsFulfillmentCosts(filter: string = ""): Promise<OperationsFulfillmentCostsResponse[]> {
  try {
    const results = await get("operationsFulfillmentCosts", { prompt: filter });
    return Array.isArray(results) ? results as OperationsFulfillmentCostsResponse[] : [];
  } catch (error) {
    console.error(`Error getting OperationsFulfillmentCosts collection at path 'operationsFulfillmentCosts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in OperationsFulfillmentCosts collection at operationsFulfillmentCosts
 
  Read Operation Details: ADMIN_ADDRESS, PROJECT_VAULT_ADDRESS, and OPERATIONS_WALLET can read fulfillment cost records for operations wallet monitoring and auditing. OPERATIONS_WALLET added for forward compatibility in case it later diverges from PROJECT_VAULT_ADDRESS.
  
 */
export function subscribeAllOperationsFulfillmentCosts(callback: (data: OperationsFulfillmentCostsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("operationsFulfillmentCosts", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as OperationsFulfillmentCostsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to OperationsFulfillmentCosts collection at path '${"operationsFulfillmentCosts"}': ${formatError(error)}`);
    }
  });
}

