// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.094Z
// Collection: packPurchases/$purchaseId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Offchain audit trail for individual pack purchases. Created and managed exclusively by the backend vault during Shopify webhook fulfillment.
 */

export interface PackPurchasesRequest {
  artistPayout: number | TimeOperation | IncrementOperation | TokenAmount;
  buyerAddress?: AddressType;
  buyerEmail: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  nftCount: number | TimeOperation | IncrementOperation | TokenAmount;
  packId: string;
  packName: string;
  platformSlice: number | TimeOperation | IncrementOperation | TokenAmount;
  shopifyOrderId: string;
  status: string;
  tokenAmount: number | TimeOperation | IncrementOperation | TokenAmount;
  songId?: string;
  nftTxHashes?: string;
  splTxHash?: string;
  artistPayoutUSD?: number | TimeOperation | IncrementOperation | TokenAmount;
  artistPayoutSOL?: number | TimeOperation | IncrementOperation | TokenAmount;
  artistPayoutStatus?: string;
  artistPayoutTxHash?: string;
  solPriceAtPurchase?: number | TimeOperation | IncrementOperation | TokenAmount;
  creatorFeeBps?: number | TimeOperation | IncrementOperation | TokenAmount;
  platformFeeBps?: number | TimeOperation | IncrementOperation | TokenAmount;
  nftRoyaltyBps?: number | TimeOperation | IncrementOperation | TokenAmount;
  infraTxHash?: string;
  nftFailedCount?: number | TimeOperation | IncrementOperation | TokenAmount;
  nftType?: string;
  mintType?: string;
  pendingOversold?: string;
  treasuryTxHash?: string;
  walletSource?: string;
  solToArtist?: number | TimeOperation | IncrementOperation | TokenAmount;
  paymentReconciliation?: string;
  stepTokens?: boolean;
  stepPayout?: boolean;
  stepNft?: boolean;
  stepNotify?: boolean;
  solPriceAtPurchaseUsd?: number | TimeOperation | IncrementOperation | TokenAmount;
  solPriceTimestamp?: number | TimeOperation | IncrementOperation | TokenAmount;
  tipPercent?: number | TimeOperation | IncrementOperation | TokenAmount;
  tipAmountUsd?: number | TimeOperation | IncrementOperation | TokenAmount;
  buyerTokenAmount?: number | TimeOperation | IncrementOperation | TokenAmount;
  artistTokenAmount?: number | TimeOperation | IncrementOperation | TokenAmount;
  treasurySlice?: number | TimeOperation | IncrementOperation | TokenAmount;
  treasuryFeeBps?: number | TimeOperation | IncrementOperation | TokenAmount;
  purchaseAmountUsd?: any;
  reconcileAttempts: number | TimeOperation | IncrementOperation | TokenAmount;
  shopifyFulfilled: boolean;
  swapTxSig: string;
  bondingCurveBuyId: string;
  artistTokenTxHash: string;
  cancelledAt?: number | TimeOperation | IncrementOperation | TokenAmount;
  cancelledBy?: AddressType;
  airdropCompleted?: boolean;
  treasuryTransferCompleted?: boolean;
  infraFeeAccounted?: boolean;
  fundingFeeAccounted?: boolean;
  bondingCurveBuySubmitted?: boolean;
  needsReviewReason?: string;
  failureReason?: string;
}

export interface PackPurchasesResponse {
  artistPayout: number;
  buyerAddress?: string;
  buyerEmail: string;
  createdAt: number;
  nftCount: number;
  packId: string;
  packName: string;
  platformSlice: number;
  shopifyOrderId: string;
  status: string;
  tokenAmount: number;
  songId?: string;
  nftTxHashes?: string;
  splTxHash?: string;
  artistPayoutUSD?: number;
  artistPayoutSOL?: number;
  artistPayoutStatus?: string;
  artistPayoutTxHash?: string;
  solPriceAtPurchase?: number;
  creatorFeeBps?: number;
  platformFeeBps?: number;
  nftRoyaltyBps?: number;
  infraTxHash?: string;
  nftFailedCount?: number;
  nftType?: string;
  mintType?: string;
  pendingOversold?: string;
  treasuryTxHash?: string;
  walletSource?: string;
  solToArtist?: number;
  paymentReconciliation?: string;
  stepTokens?: boolean;
  stepPayout?: boolean;
  stepNft?: boolean;
  stepNotify?: boolean;
  solPriceAtPurchaseUsd?: number;
  solPriceTimestamp?: number;
  tipPercent?: number;
  tipAmountUsd?: number;
  buyerTokenAmount?: number;
  artistTokenAmount?: number;
  treasurySlice?: number;
  treasuryFeeBps?: number;
  purchaseAmountUsd?: any;
  reconcileAttempts: number;
  shopifyFulfilled: boolean;
  swapTxSig: string;
  bondingCurveBuyId: string;
  artistTokenTxHash: string;
  cancelledAt?: number;
  cancelledBy?: string;
  airdropCompleted?: boolean;
  treasuryTransferCompleted?: boolean;
  infraFeeAccounted?: boolean;
  fundingFeeAccounted?: boolean;
  bondingCurveBuySubmitted?: boolean;
  needsReviewReason?: string;
  failureReason?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PackPurchases operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPackPurchases(purchaseId: string, data: PackPurchasesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `packPurchases/${purchaseId}`, document: doc };
}

/**
 * The backend signer (either PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET) can create purchase records when Shopify webhooks are received, but ONLY if no document already exists at this path (get(/packPurchases/$purchaseId) == null). Because purchase document IDs are deterministic ('pack-{shopifyOrderId}-{packId}'), this enforces a hard uniqueness constraint on the (shopifyOrderId, packId) tuple at the policy layer — a second creator racing the webhook handler's pre-create existence check will hard-fail rather than silently succeed/overwrite. Accepting both backend constants ensures fulfillment continues to work if OPERATIONS_WALLET is later repointed to a separate signer. Optional fields walletSource, nftType, mintType, infraTxHash, treasuryTxHash, pendingOversold, nftFailedCount, creatorFeeBps, platformFeeBps, treasuryFeeBps, nftRoyaltyBps, solPriceAtPurchaseUsd, solPriceTimestamp, tipPercent, tipAmountUsd, buyerTokenAmount, artistTokenAmount, treasurySlice, purchaseAmountUsd (exact USD amount fan chose to spend, read from Shopify cart attribute amountUsd), and idempotency step flags (stepTokens, stepPayout, stepNft, stepNotify) are written by the backend during fulfillment. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPackPurchases(purchaseId: string, data: PackPurchasesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`packPurchases/${purchaseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PackPurchases: ${formatError(error)}`);
    return false;
  }
}

export type PackPurchasesRequestUpdate = Partial<PackPurchasesRequest>;

/**
 * Build a PackPurchases update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePackPurchases(purchaseId: string, data: PackPurchasesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `packPurchases/${purchaseId}`, document: doc };
}

/**
 * The backend signer (either PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET) can update purchase records, typically to transition status through the fulfillment lifecycle. Accepting both constants ensures fulfillment continues to work if OPERATIONS_WALLET is later repointed to a separate signer. treasuryFeeBps stores the treasury fee in basis points captured at purchase time alongside creatorFeeBps, platformFeeBps, and nftRoyaltyBps. All fee-bps fields are optional UInt and written by the backend during payout validation. purchaseAmountUsd stores the exact USD amount the fan chose to spend at checkout (source-of-truth for downstream token math). Step flags (stepTokens, stepPayout, stepNft, stepNotify) are toggled to true as each fulfillment step completes; resume endpoint uses these to retry only steps still false. Idempotency flags airdropCompleted, treasuryTransferCompleted, infraFeeAccounted, and fundingFeeAccounted are set to true by fulfillment-steps.ts as each corresponding step (token airdrop, treasury outbound transfer, infra fee accounting, funding fee accounting) succeeds; fulfillment skips already-completed steps on retry. cancelledAt and cancelledBy are set together when an admin cancels a stuck order via the cancel endpoint; status is also set to 'cancelled' in the same write. Webhook re-delivery detection treats records with status='cancelled' as terminal and skips re-fulfillment. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePackPurchases(purchaseId: string, data: PackPurchasesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`packPurchases/${purchaseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PackPurchases: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: PROJECT_VAULT_ADDRESS, OPERATIONS_WALLET, and ADMIN_ADDRESS can read all purchase records for backend fulfillment, retries, and auditing. Backend signs Tarobase requests with PROJECT_VAULT_ADDRESS/OPERATIONS_WALLET (same wallet 9LLTjsWh...) to read purchase state during webhook processing and resume flows.
   (Get Single Item)
 */
export async function getPackPurchases(purchaseId: string): Promise<PackPurchasesResponse | null> {
  try {
    const result = await get(`packPurchases/${purchaseId}`);
    return result as PackPurchasesResponse | null;
  } catch (error) {
    console.error(`Error getting PackPurchases: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PackPurchases document. (
  Read Operation Details: PROJECT_VAULT_ADDRESS, OPERATIONS_WALLET, and ADMIN_ADDRESS can read all purchase records for backend fulfillment, retries, and auditing. Backend signs Tarobase requests with PROJECT_VAULT_ADDRESS/OPERATIONS_WALLET (same wallet 9LLTjsWh...) to read purchase state during webhook processing and resume flows.
  )
 */
export function subscribePackPurchases(callback: (data: PackPurchasesResponse | null) => void, purchaseId: string): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/${purchaseId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PackPurchasesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PackPurchases at path '${`packPurchases/${purchaseId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PackPurchases items from collection packPurchases
 
  Read Operation Details: PROJECT_VAULT_ADDRESS, OPERATIONS_WALLET, and ADMIN_ADDRESS can read all purchase records for backend fulfillment, retries, and auditing. Backend signs Tarobase requests with PROJECT_VAULT_ADDRESS/OPERATIONS_WALLET (same wallet 9LLTjsWh...) to read purchase state during webhook processing and resume flows.
  
 */
export async function getManyPackPurchases(filter: string = ""): Promise<PackPurchasesResponse[]> {
  try {
    const results = await get("packPurchases", { prompt: filter });
    return Array.isArray(results) ? results as PackPurchasesResponse[] : [];
  } catch (error) {
    console.error(`Error getting PackPurchases collection at path 'packPurchases': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PackPurchases collection at packPurchases
 
  Read Operation Details: PROJECT_VAULT_ADDRESS, OPERATIONS_WALLET, and ADMIN_ADDRESS can read all purchase records for backend fulfillment, retries, and auditing. Backend signs Tarobase requests with PROJECT_VAULT_ADDRESS/OPERATIONS_WALLET (same wallet 9LLTjsWh...) to read purchase state during webhook processing and resume flows.
  
 */
export function subscribeManyPackPurchases(callback: (data: PackPurchasesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("packPurchases", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PackPurchasesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PackPurchases collection at path '${"packPurchases"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PackPurchases items from collection packPurchases
 
  Read Operation Details: PROJECT_VAULT_ADDRESS, OPERATIONS_WALLET, and ADMIN_ADDRESS can read all purchase records for backend fulfillment, retries, and auditing. Backend signs Tarobase requests with PROJECT_VAULT_ADDRESS/OPERATIONS_WALLET (same wallet 9LLTjsWh...) to read purchase state during webhook processing and resume flows.
  
 */
export async function getAllPackPurchases(filter: string = ""): Promise<PackPurchasesResponse[]> {
  try {
    const results = await get("packPurchases", { prompt: filter });
    return Array.isArray(results) ? results as PackPurchasesResponse[] : [];
  } catch (error) {
    console.error(`Error getting PackPurchases collection at path 'packPurchases': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PackPurchases collection at packPurchases
 
  Read Operation Details: PROJECT_VAULT_ADDRESS, OPERATIONS_WALLET, and ADMIN_ADDRESS can read all purchase records for backend fulfillment, retries, and auditing. Backend signs Tarobase requests with PROJECT_VAULT_ADDRESS/OPERATIONS_WALLET (same wallet 9LLTjsWh...) to read purchase state during webhook processing and resume flows.
  
 */
export function subscribeAllPackPurchases(callback: (data: PackPurchasesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("packPurchases", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PackPurchasesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PackPurchases collection at path '${"packPurchases"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Admin-only deletion. PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET can delete pack purchase records. Used by the Admin UI's Stuck Orders tab to remove stuck or permanently failed order records that cannot be recovered.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePackPurchases(purchaseId: string): Promise<boolean> {
  try {
    const succeeded = await set(`packPurchases/${purchaseId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PackPurchases: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PackPurchases for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePackPurchases(purchaseId: string): DocumentOperation {
  return { path: `packPurchases/${purchaseId}`, document: null };
}


/**
 * Artist SOL payout triggered by webhook for pack purchases. Transfers 69% of pack price from OPERATIONS_WALLET to song creator.
 */

export interface PackPurchasesPayoutsRequest {
  recipient: AddressType;
  solAmt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PackPurchasesPayoutsResponse {
  recipient: string;
  solAmt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PackPurchasesPayouts operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPackPurchasesPayouts(purchaseId: string, payoutId: string, data?: PackPurchasesPayoutsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `packPurchases/${purchaseId}/payouts/${payoutId}`, document: doc };
}

/**
 * Only PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET can trigger payout. Called from backend webhook. The hook transfers SOL from OPERATIONS_WALLET to @newData.recipient. solAmt is in lamports. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPackPurchasesPayouts(purchaseId: string, payoutId: string, data?: PackPurchasesPayoutsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`packPurchases/${purchaseId}/payouts/${payoutId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PackPurchasesPayouts: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
   (Get Single Item)
 */
export async function getPackPurchasesPayouts(purchaseId: string, payoutId: string): Promise<PackPurchasesPayoutsResponse | null> {
  try {
    const result = await get(`packPurchases/${purchaseId}/payouts/${payoutId}`);
    return result as PackPurchasesPayoutsResponse | null;
  } catch (error) {
    console.error(`Error getting PackPurchasesPayouts: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PackPurchasesPayouts document. (
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  )
 */
export function subscribePackPurchasesPayouts(callback: (data: PackPurchasesPayoutsResponse | null) => void, purchaseId: string, payoutId: string): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/${purchaseId}/payouts/${payoutId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PackPurchasesPayoutsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PackPurchasesPayouts at path '${`packPurchases/${purchaseId}/payouts/${payoutId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PackPurchasesPayouts items from collection packPurchases/${purchaseId}/payouts
 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  
 */
export async function getManyPackPurchasesPayouts(purchaseId: string, filter: string = ""): Promise<PackPurchasesPayoutsResponse[]> {
  try {
    const results = await get(`packPurchases/${purchaseId}/payouts`, { prompt: filter });
    return Array.isArray(results) ? results as PackPurchasesPayoutsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PackPurchasesPayouts collection at path 'packPurchases/${purchaseId}/payouts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PackPurchasesPayouts collection at packPurchases/${purchaseId}/payouts
 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  
 */
export function subscribeManyPackPurchasesPayouts(callback: (data: PackPurchasesPayoutsResponse[]) => void, purchaseId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/${purchaseId}/payouts`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PackPurchasesPayoutsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PackPurchasesPayouts collection at path '${`packPurchases/${purchaseId}/payouts`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PackPurchasesPayouts items from collection packPurchases/${purchaseId}/payouts
 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  
 */
export async function getAllPackPurchasesPayouts(purchaseId: string, filter: string = ""): Promise<PackPurchasesPayoutsResponse[]> {
  try {
    const results = await get(`packPurchases/*/payouts`, { prompt: filter });
    return Array.isArray(results) ? results as PackPurchasesPayoutsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PackPurchasesPayouts collection at path 'packPurchases/${purchaseId}/payouts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PackPurchasesPayouts collection at packPurchases/${purchaseId}/payouts
 
  Read Operation Details: Public read. Anyone can inspect artist payout records.
  
 */
export function subscribeAllPackPurchasesPayouts(callback: (data: PackPurchasesPayoutsResponse[]) => void, purchaseId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/*/payouts`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PackPurchasesPayoutsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PackPurchasesPayouts collection at path '${`packPurchases/*/payouts`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PackPurchasesPayouts items in collection packPurchases/${purchaseId}/payouts.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPackPurchasesPayouts(purchaseId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`packPurchases/${purchaseId}/payouts`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PackPurchasesPayouts at path 'packPurchases/${purchaseId}/payouts': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PackPurchasesPayouts items in collection packPurchases/${purchaseId}/payouts.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePackPurchasesPayouts(purchaseId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`packPurchases/${purchaseId}/payouts`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PackPurchasesPayouts at path 'packPurchases/${purchaseId}/payouts': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Infrastructure fee 10% of pack price from OPERATIONS_WALLET to infrastructure wallet for pack purchases.
 */

export interface PackPurchasesInfraFeesRequest {
  recipient: AddressType;
  solAmt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PackPurchasesInfraFeesResponse {
  recipient: string;
  solAmt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PackPurchasesInfraFees operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPackPurchasesInfraFees(purchaseId: string, feeId: string, data?: PackPurchasesInfraFeesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `packPurchases/${purchaseId}/infraFees/${feeId}`, document: doc };
}

/**
 * Only PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET can trigger payout. Called from backend webhook. The hook transfers SOL from OPERATIONS_WALLET to @newData.recipient. solAmt is in lamports. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPackPurchasesInfraFees(purchaseId: string, feeId: string, data?: PackPurchasesInfraFeesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`packPurchases/${purchaseId}/infraFees/${feeId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PackPurchasesInfraFees: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
   (Get Single Item)
 */
export async function getPackPurchasesInfraFees(purchaseId: string, feeId: string): Promise<PackPurchasesInfraFeesResponse | null> {
  try {
    const result = await get(`packPurchases/${purchaseId}/infraFees/${feeId}`);
    return result as PackPurchasesInfraFeesResponse | null;
  } catch (error) {
    console.error(`Error getting PackPurchasesInfraFees: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PackPurchasesInfraFees document. (
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  )
 */
export function subscribePackPurchasesInfraFees(callback: (data: PackPurchasesInfraFeesResponse | null) => void, purchaseId: string, feeId: string): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/${purchaseId}/infraFees/${feeId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PackPurchasesInfraFeesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PackPurchasesInfraFees at path '${`packPurchases/${purchaseId}/infraFees/${feeId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PackPurchasesInfraFees items from collection packPurchases/${purchaseId}/infraFees
 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  
 */
export async function getManyPackPurchasesInfraFees(purchaseId: string, filter: string = ""): Promise<PackPurchasesInfraFeesResponse[]> {
  try {
    const results = await get(`packPurchases/${purchaseId}/infraFees`, { prompt: filter });
    return Array.isArray(results) ? results as PackPurchasesInfraFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting PackPurchasesInfraFees collection at path 'packPurchases/${purchaseId}/infraFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PackPurchasesInfraFees collection at packPurchases/${purchaseId}/infraFees
 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  
 */
export function subscribeManyPackPurchasesInfraFees(callback: (data: PackPurchasesInfraFeesResponse[]) => void, purchaseId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/${purchaseId}/infraFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PackPurchasesInfraFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PackPurchasesInfraFees collection at path '${`packPurchases/${purchaseId}/infraFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PackPurchasesInfraFees items from collection packPurchases/${purchaseId}/infraFees
 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  
 */
export async function getAllPackPurchasesInfraFees(purchaseId: string, filter: string = ""): Promise<PackPurchasesInfraFeesResponse[]> {
  try {
    const results = await get(`packPurchases/*/infraFees`, { prompt: filter });
    return Array.isArray(results) ? results as PackPurchasesInfraFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting PackPurchasesInfraFees collection at path 'packPurchases/${purchaseId}/infraFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PackPurchasesInfraFees collection at packPurchases/${purchaseId}/infraFees
 
  Read Operation Details: Public read. Anyone can inspect infrastructure fee records.
  
 */
export function subscribeAllPackPurchasesInfraFees(callback: (data: PackPurchasesInfraFeesResponse[]) => void, purchaseId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/*/infraFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PackPurchasesInfraFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PackPurchasesInfraFees collection at path '${`packPurchases/*/infraFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PackPurchasesInfraFees items in collection packPurchases/${purchaseId}/infraFees.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPackPurchasesInfraFees(purchaseId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`packPurchases/${purchaseId}/infraFees`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PackPurchasesInfraFees at path 'packPurchases/${purchaseId}/infraFees': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PackPurchasesInfraFees items in collection packPurchases/${purchaseId}/infraFees.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePackPurchasesInfraFees(purchaseId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`packPurchases/${purchaseId}/infraFees`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PackPurchasesInfraFees at path 'packPurchases/${purchaseId}/infraFees': ${formatError(error)}`);
    return { value: 0 };
  }
}


/**
 * Treasury fee 1% of pack price from OPERATIONS_WALLET to treasury wallet for pack purchases.
 */

export interface PackPurchasesTreasuryFeesRequest {
  recipient: AddressType;
  solAmt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PackPurchasesTreasuryFeesResponse {
  recipient: string;
  solAmt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a PackPurchasesTreasuryFees operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPackPurchasesTreasuryFees(purchaseId: string, feeId: string, data?: PackPurchasesTreasuryFeesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `packPurchases/${purchaseId}/treasuryFees/${feeId}`, document: doc };
}

/**
 * Only PROJECT_VAULT_ADDRESS or OPERATIONS_WALLET can trigger payout. Called from backend webhook. The hook transfers SOL from OPERATIONS_WALLET to @newData.recipient. solAmt is in lamports. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPackPurchasesTreasuryFees(purchaseId: string, feeId: string, data?: PackPurchasesTreasuryFeesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`packPurchases/${purchaseId}/treasuryFees/${feeId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PackPurchasesTreasuryFees: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
   (Get Single Item)
 */
export async function getPackPurchasesTreasuryFees(purchaseId: string, feeId: string): Promise<PackPurchasesTreasuryFeesResponse | null> {
  try {
    const result = await get(`packPurchases/${purchaseId}/treasuryFees/${feeId}`);
    return result as PackPurchasesTreasuryFeesResponse | null;
  } catch (error) {
    console.error(`Error getting PackPurchasesTreasuryFees: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PackPurchasesTreasuryFees document. (
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  )
 */
export function subscribePackPurchasesTreasuryFees(callback: (data: PackPurchasesTreasuryFeesResponse | null) => void, purchaseId: string, feeId: string): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/${purchaseId}/treasuryFees/${feeId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PackPurchasesTreasuryFeesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PackPurchasesTreasuryFees at path '${`packPurchases/${purchaseId}/treasuryFees/${feeId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PackPurchasesTreasuryFees items from collection packPurchases/${purchaseId}/treasuryFees
 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  
 */
export async function getManyPackPurchasesTreasuryFees(purchaseId: string, filter: string = ""): Promise<PackPurchasesTreasuryFeesResponse[]> {
  try {
    const results = await get(`packPurchases/${purchaseId}/treasuryFees`, { prompt: filter });
    return Array.isArray(results) ? results as PackPurchasesTreasuryFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting PackPurchasesTreasuryFees collection at path 'packPurchases/${purchaseId}/treasuryFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PackPurchasesTreasuryFees collection at packPurchases/${purchaseId}/treasuryFees
 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  
 */
export function subscribeManyPackPurchasesTreasuryFees(callback: (data: PackPurchasesTreasuryFeesResponse[]) => void, purchaseId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/${purchaseId}/treasuryFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PackPurchasesTreasuryFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PackPurchasesTreasuryFees collection at path '${`packPurchases/${purchaseId}/treasuryFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PackPurchasesTreasuryFees items from collection packPurchases/${purchaseId}/treasuryFees
 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  
 */
export async function getAllPackPurchasesTreasuryFees(purchaseId: string, filter: string = ""): Promise<PackPurchasesTreasuryFeesResponse[]> {
  try {
    const results = await get(`packPurchases/*/treasuryFees`, { prompt: filter });
    return Array.isArray(results) ? results as PackPurchasesTreasuryFeesResponse[] : [];
  } catch (error) {
    console.error(`Error getting PackPurchasesTreasuryFees collection at path 'packPurchases/${purchaseId}/treasuryFees': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PackPurchasesTreasuryFees collection at packPurchases/${purchaseId}/treasuryFees
 
  Read Operation Details: Public read. Anyone can inspect treasury fee records.
  
 */
export function subscribeAllPackPurchasesTreasuryFees(callback: (data: PackPurchasesTreasuryFeesResponse[]) => void, purchaseId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`packPurchases/*/treasuryFees`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PackPurchasesTreasuryFeesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PackPurchasesTreasuryFees collection at path '${`packPurchases/*/treasuryFees`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count PackPurchasesTreasuryFees items in collection packPurchases/${purchaseId}/treasuryFees.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countPackPurchasesTreasuryFees(purchaseId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`packPurchases/${purchaseId}/treasuryFees`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting PackPurchasesTreasuryFees at path 'packPurchases/${purchaseId}/treasuryFees': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on PackPurchasesTreasuryFees items in collection packPurchases/${purchaseId}/treasuryFees.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregatePackPurchasesTreasuryFees(purchaseId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`packPurchases/${purchaseId}/treasuryFees`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating PackPurchasesTreasuryFees at path 'packPurchases/${purchaseId}/treasuryFees': ${formatError(error)}`);
    return { value: 0 };
  }
}

