// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: portfolioHistory/$userAddress/snapshots/$snapshotId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Historical portfolio value snapshots per user
 */

export interface PortfolioHistorySnapshotsRequest {
  valueUsd: number | TimeOperation | IncrementOperation | TokenAmount;
  solValue: number | TimeOperation | IncrementOperation | TokenAmount;
  tokenValue: number | TimeOperation | IncrementOperation | TokenAmount;
  timestamp: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PortfolioHistorySnapshotsResponse {
  valueUsd: number;
  solValue: number;
  tokenValue: number;
  timestamp: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PortfolioHistorySnapshots operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPortfolioHistorySnapshots(userAddress: string, snapshotId: string, data: PortfolioHistorySnapshotsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `portfolioHistory/${userAddress}/snapshots/${snapshotId}`, document: doc };
}

/**
 * Users can only create snapshots for their own address. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPortfolioHistorySnapshots(userAddress: string, snapshotId: string, data: PortfolioHistorySnapshotsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`portfolioHistory/${userAddress}/snapshots/${snapshotId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PortfolioHistorySnapshots: ${formatError(error)}`);
    return false;
  }
}

export type PortfolioHistorySnapshotsRequestUpdate = Partial<PortfolioHistorySnapshotsRequest>;

/**
 * Build a PortfolioHistorySnapshots update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePortfolioHistorySnapshots(userAddress: string, snapshotId: string, data: PortfolioHistorySnapshotsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `portfolioHistory/${userAddress}/snapshots/${snapshotId}`, document: doc };
}

/**
 * Users can only update their own snapshots. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePortfolioHistorySnapshots(userAddress: string, snapshotId: string, data: PortfolioHistorySnapshotsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`portfolioHistory/${userAddress}/snapshots/${snapshotId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PortfolioHistorySnapshots: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Users can only read their own portfolio history snapshots.
   (Get Single Item)
 */
export async function getPortfolioHistorySnapshots(userAddress: string, snapshotId: string): Promise<PortfolioHistorySnapshotsResponse | null> {
  try {
    const result = await get(`portfolioHistory/${userAddress}/snapshots/${snapshotId}`);
    return result as PortfolioHistorySnapshotsResponse | null;
  } catch (error) {
    console.error(`Error getting PortfolioHistorySnapshots: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PortfolioHistorySnapshots document. (
  Read Operation Details: Users can only read their own portfolio history snapshots.
  )
 */
export function subscribePortfolioHistorySnapshots(callback: (data: PortfolioHistorySnapshotsResponse | null) => void, userAddress: string, snapshotId: string): Promise<() => Promise<void>> {
  return subscribe(`portfolioHistory/${userAddress}/snapshots/${snapshotId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PortfolioHistorySnapshotsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PortfolioHistorySnapshots at path '${`portfolioHistory/${userAddress}/snapshots/${snapshotId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PortfolioHistorySnapshots items from collection portfolioHistory/${userAddress}/snapshots
 
  Read Operation Details: Users can only read their own portfolio history snapshots.
  
 */
export async function getManyPortfolioHistorySnapshots(userAddress: string, filter: string = ""): Promise<PortfolioHistorySnapshotsResponse[]> {
  try {
    const results = await get(`portfolioHistory/${userAddress}/snapshots`, { prompt: filter });
    return Array.isArray(results) ? results as PortfolioHistorySnapshotsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PortfolioHistorySnapshots collection at path 'portfolioHistory/${userAddress}/snapshots': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PortfolioHistorySnapshots collection at portfolioHistory/${userAddress}/snapshots
 
  Read Operation Details: Users can only read their own portfolio history snapshots.
  
 */
export function subscribeManyPortfolioHistorySnapshots(callback: (data: PortfolioHistorySnapshotsResponse[]) => void, userAddress: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`portfolioHistory/${userAddress}/snapshots`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PortfolioHistorySnapshotsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PortfolioHistorySnapshots collection at path '${`portfolioHistory/${userAddress}/snapshots`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PortfolioHistorySnapshots items from collection portfolioHistory/${userAddress}/snapshots
 
  Read Operation Details: Users can only read their own portfolio history snapshots.
  
 */
export async function getAllPortfolioHistorySnapshots(userAddress: string, filter: string = ""): Promise<PortfolioHistorySnapshotsResponse[]> {
  try {
    const results = await get(`portfolioHistory/*/snapshots`, { prompt: filter });
    return Array.isArray(results) ? results as PortfolioHistorySnapshotsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PortfolioHistorySnapshots collection at path 'portfolioHistory/${userAddress}/snapshots': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PortfolioHistorySnapshots collection at portfolioHistory/${userAddress}/snapshots
 
  Read Operation Details: Users can only read their own portfolio history snapshots.
  
 */
export function subscribeAllPortfolioHistorySnapshots(callback: (data: PortfolioHistorySnapshotsResponse[]) => void, userAddress: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`portfolioHistory/*/snapshots`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PortfolioHistorySnapshotsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PortfolioHistorySnapshots collection at path '${`portfolioHistory/*/snapshots`}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Users can only delete their own snapshots.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePortfolioHistorySnapshots(userAddress: string, snapshotId: string): Promise<boolean> {
  try {
    const succeeded = await set(`portfolioHistory/${userAddress}/snapshots/${snapshotId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PortfolioHistorySnapshots: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PortfolioHistorySnapshots for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePortfolioHistorySnapshots(userAddress: string, snapshotId: string): DocumentOperation {
  return { path: `portfolioHistory/${userAddress}/snapshots/${snapshotId}`, document: null };
}

