// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.094Z
// Collection: purchases/$purchaseId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Audit trail for Shopify webhook purchases. Only the backend (PROJECT_VAULT_ADDRESS) can create and update these records.
 */

export interface PurchasesRequest {
  email: string;
  orderId: string;
  songId?: string;
  walletAddress?: string;
  tokenAmount?: number | TimeOperation | IncrementOperation | TokenAmount;
  status: string;
  shopifyPayload?: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  nftCount?: number | TimeOperation | IncrementOperation | TokenAmount;
  nftTxHashes?: string;
  artistPayout?: number | TimeOperation | IncrementOperation | TokenAmount;
  platformFee?: number | TimeOperation | IncrementOperation | TokenAmount;
  receiptData?: string;
  packAmountUsd?: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PurchasesResponse {
  email: string;
  orderId: string;
  songId?: string;
  walletAddress?: string;
  tokenAmount?: number;
  status: string;
  shopifyPayload?: string;
  createdAt: number;
  nftCount?: number;
  nftTxHashes?: string;
  artistPayout?: number;
  platformFee?: number;
  receiptData?: string;
  packAmountUsd?: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Purchases operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPurchases(purchaseId: string, data: PurchasesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `purchases/${purchaseId}`, document: doc };
}

/**
 * Only the backend (PROJECT_VAULT_ADDRESS) can create purchase records when Shopify webhooks are received. email and orderId are immutable after creation. status should be 'pending', 'completed', or 'failed'. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPurchases(purchaseId: string, data: PurchasesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`purchases/${purchaseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Purchases: ${formatError(error)}`);
    return false;
  }
}

export type PurchasesRequestUpdate = Partial<PurchasesRequest>;

/**
 * Build a Purchases update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePurchases(purchaseId: string, data: PurchasesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `purchases/${purchaseId}`, document: doc };
}

/**
 * Only the backend can update purchase records, typically to change status from 'pending' to 'completed' or 'failed' and to set walletAddress and tokenAmount after airdrop. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePurchases(purchaseId: string, data: PurchasesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`purchases/${purchaseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Purchases: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Only admin and backend vault can read purchase records for auditing and backend processing.
   (Get Single Item)
 */
export async function getPurchases(purchaseId: string): Promise<PurchasesResponse | null> {
  try {
    const result = await get(`purchases/${purchaseId}`);
    return result as PurchasesResponse | null;
  } catch (error) {
    console.error(`Error getting Purchases: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Purchases document. (
  Read Operation Details: Only admin and backend vault can read purchase records for auditing and backend processing.
  )
 */
export function subscribePurchases(callback: (data: PurchasesResponse | null) => void, purchaseId: string): Promise<() => Promise<void>> {
  return subscribe(`purchases/${purchaseId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PurchasesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Purchases at path '${`purchases/${purchaseId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Purchases items from collection purchases
 
  Read Operation Details: Only admin and backend vault can read purchase records for auditing and backend processing.
  
 */
export async function getManyPurchases(filter: string = ""): Promise<PurchasesResponse[]> {
  try {
    const results = await get("purchases", { prompt: filter });
    return Array.isArray(results) ? results as PurchasesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Purchases collection at path 'purchases': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Purchases collection at purchases
 
  Read Operation Details: Only admin and backend vault can read purchase records for auditing and backend processing.
  
 */
export function subscribeManyPurchases(callback: (data: PurchasesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("purchases", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PurchasesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Purchases collection at path '${"purchases"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Purchases items from collection purchases
 
  Read Operation Details: Only admin and backend vault can read purchase records for auditing and backend processing.
  
 */
export async function getAllPurchases(filter: string = ""): Promise<PurchasesResponse[]> {
  try {
    const results = await get("purchases", { prompt: filter });
    return Array.isArray(results) ? results as PurchasesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Purchases collection at path 'purchases': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Purchases collection at purchases
 
  Read Operation Details: Only admin and backend vault can read purchase records for auditing and backend processing.
  
 */
export function subscribeAllPurchases(callback: (data: PurchasesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("purchases", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PurchasesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Purchases collection at path '${"purchases"}': ${formatError(error)}`);
    }
  });
}

