// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: recoveryTransfers/$recoveryId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin-only onchain recovery transfers. Replaces the legacy raw-signed SPL transfer in the admin recovery API route. Creating a document atomically transfers @newData.amount of @newData.mintAddress from PROJECT_VAULT_ADDRESS to @newData.buyerAddress via @TokenPlugin.transfer, enforcing policy/audit/immutability the same way every other vault-signed token movement in this app does (see songs/$songId/airdrops/$airdropId).
 */

export interface RecoveryTransfersRequest {
  purchaseId: string;
  buyerAddress: AddressType;
  mintAddress: AddressType;
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  reason: string;
  status: string;
  txSignature?: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  createdBy: AddressType;
}

export interface RecoveryTransfersResponse {
  purchaseId: string;
  buyerAddress: string;
  mintAddress: string;
  amount: number;
  reason: string;
  status: string;
  txSignature?: string;
  createdAt: number;
  createdBy: string;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a RecoveryTransfers operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildRecoveryTransfers(recoveryId: string, data?: RecoveryTransfersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `recoveryTransfers/${recoveryId}`, document: doc };
}

/**
 * ONLY @constants.ADMIN_ADDRESS may create a recovery transfer. Admin MUST set createdBy == @constants.ADMIN_ADDRESS at create time (rule-enforced, prevents impersonation in audit trail). Creating the document atomically invokes the onchain hook: @TokenPlugin.transfer(PROJECT_VAULT_ADDRESS, buyerAddress, mintAddress, amount) — same vault-signing convention as songs/$songId/airdrops/$airdropId. If the transfer fails, document creation fails (atomic). If the document exists, the transfer succeeded onchain — admin should set status='pending' at create time; the real onchain success signal is the auto-populated tarobase_transaction_hash field. The optional txSignature field is reserved for callers who want to denormalize the signature at create time; otherwise rely on tarobase_transaction_hash. createdAt is Unix seconds at create. reason is a short admin-supplied tag (e.g. 'stuck_after_swap', 'partial_failure_recovery'). amount is in the token's smallest base units (matches songs/$songId/airdrops/$airdropId convention). purchaseId references the packPurchases/$purchaseId document being recovered. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setRecoveryTransfers(recoveryId: string, data?: RecoveryTransfersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`recoveryTransfers/${recoveryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting RecoveryTransfers: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read (required because onchain data is inherently public on the blockchain). Anyone can inspect recovery transfer records. Sensitive operational context lives in the offchain packPurchases/$purchaseId record referenced by purchaseId.
   (Get Single Item)
 */
export async function getRecoveryTransfers(recoveryId: string): Promise<RecoveryTransfersResponse | null> {
  try {
    const result = await get(`recoveryTransfers/${recoveryId}`);
    return result as RecoveryTransfersResponse | null;
  } catch (error) {
    console.error(`Error getting RecoveryTransfers: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single RecoveryTransfers document. (
  Read Operation Details: Public read (required because onchain data is inherently public on the blockchain). Anyone can inspect recovery transfer records. Sensitive operational context lives in the offchain packPurchases/$purchaseId record referenced by purchaseId.
  )
 */
export function subscribeRecoveryTransfers(callback: (data: RecoveryTransfersResponse | null) => void, recoveryId: string): Promise<() => Promise<void>> {
  return subscribe(`recoveryTransfers/${recoveryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as RecoveryTransfersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to RecoveryTransfers at path '${`recoveryTransfers/${recoveryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many RecoveryTransfers items from collection recoveryTransfers
 
  Read Operation Details: Public read (required because onchain data is inherently public on the blockchain). Anyone can inspect recovery transfer records. Sensitive operational context lives in the offchain packPurchases/$purchaseId record referenced by purchaseId.
  
 */
export async function getManyRecoveryTransfers(filter: string = ""): Promise<RecoveryTransfersResponse[]> {
  try {
    const results = await get("recoveryTransfers", { prompt: filter });
    return Array.isArray(results) ? results as RecoveryTransfersResponse[] : [];
  } catch (error) {
    console.error(`Error getting RecoveryTransfers collection at path 'recoveryTransfers': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in RecoveryTransfers collection at recoveryTransfers
 
  Read Operation Details: Public read (required because onchain data is inherently public on the blockchain). Anyone can inspect recovery transfer records. Sensitive operational context lives in the offchain packPurchases/$purchaseId record referenced by purchaseId.
  
 */
export function subscribeManyRecoveryTransfers(callback: (data: RecoveryTransfersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("recoveryTransfers", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RecoveryTransfersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to RecoveryTransfers collection at path '${"recoveryTransfers"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all RecoveryTransfers items from collection recoveryTransfers
 
  Read Operation Details: Public read (required because onchain data is inherently public on the blockchain). Anyone can inspect recovery transfer records. Sensitive operational context lives in the offchain packPurchases/$purchaseId record referenced by purchaseId.
  
 */
export async function getAllRecoveryTransfers(filter: string = ""): Promise<RecoveryTransfersResponse[]> {
  try {
    const results = await get("recoveryTransfers", { prompt: filter });
    return Array.isArray(results) ? results as RecoveryTransfersResponse[] : [];
  } catch (error) {
    console.error(`Error getting RecoveryTransfers collection at path 'recoveryTransfers': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in RecoveryTransfers collection at recoveryTransfers
 
  Read Operation Details: Public read (required because onchain data is inherently public on the blockchain). Anyone can inspect recovery transfer records. Sensitive operational context lives in the offchain packPurchases/$purchaseId record referenced by purchaseId.
  
 */
export function subscribeAllRecoveryTransfers(callback: (data: RecoveryTransfersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("recoveryTransfers", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RecoveryTransfersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to RecoveryTransfers collection at path '${"recoveryTransfers"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count RecoveryTransfers items in collection recoveryTransfers.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countRecoveryTransfers(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("recoveryTransfers", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting RecoveryTransfers at path 'recoveryTransfers': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on RecoveryTransfers items in collection recoveryTransfers.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateRecoveryTransfers(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("recoveryTransfers", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating RecoveryTransfers at path 'recoveryTransfers': ${formatError(error)}`);
    return { value: 0 };
  }
}

