// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: reposts/$repostId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks reposts of songs by users. Used to count reposts per song and list a user's reposts on their profile. Public read for leaderboards/counts; create restricted to the reposter; immutable updates; only the reposter can delete (un-repost).
 */

export interface RepostsRequest {
  songId: string;
  reposterAddress: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface RepostsResponse {
  songId: string;
  reposterAddress: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Reposts operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildReposts(repostId: string, data: RepostsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `reposts/${repostId}`, document: doc };
}

/**
 * Any authenticated user can create a repost. Caller must set reposterAddress to their own wallet (@newData.reposterAddress == @user.address). Frontend should set createdAt to current Unix seconds. Document ID is application-defined (typically '{songId}_{reposterAddress}' or a generated id). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setReposts(repostId: string, data: RepostsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`reposts/${repostId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Reposts: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read all reposts. Used for public reposter lists, per-song repost counts on leaderboards, and per-user repost lists on profiles.
   (Get Single Item)
 */
export async function getReposts(repostId: string): Promise<RepostsResponse | null> {
  try {
    const result = await get(`reposts/${repostId}`);
    return result as RepostsResponse | null;
  } catch (error) {
    console.error(`Error getting Reposts: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Reposts document. (
  Read Operation Details: Anyone can read all reposts. Used for public reposter lists, per-song repost counts on leaderboards, and per-user repost lists on profiles.
  )
 */
export function subscribeReposts(callback: (data: RepostsResponse | null) => void, repostId: string): Promise<() => Promise<void>> {
  return subscribe(`reposts/${repostId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as RepostsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Reposts at path '${`reposts/${repostId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Reposts items from collection reposts
 
  Read Operation Details: Anyone can read all reposts. Used for public reposter lists, per-song repost counts on leaderboards, and per-user repost lists on profiles.
  
 */
export async function getManyReposts(filter: string = ""): Promise<RepostsResponse[]> {
  try {
    const results = await get("reposts", { prompt: filter });
    return Array.isArray(results) ? results as RepostsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Reposts collection at path 'reposts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Reposts collection at reposts
 
  Read Operation Details: Anyone can read all reposts. Used for public reposter lists, per-song repost counts on leaderboards, and per-user repost lists on profiles.
  
 */
export function subscribeManyReposts(callback: (data: RepostsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("reposts", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RepostsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Reposts collection at path '${"reposts"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Reposts items from collection reposts
 
  Read Operation Details: Anyone can read all reposts. Used for public reposter lists, per-song repost counts on leaderboards, and per-user repost lists on profiles.
  
 */
export async function getAllReposts(filter: string = ""): Promise<RepostsResponse[]> {
  try {
    const results = await get("reposts", { prompt: filter });
    return Array.isArray(results) ? results as RepostsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Reposts collection at path 'reposts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Reposts collection at reposts
 
  Read Operation Details: Anyone can read all reposts. Used for public reposter lists, per-song repost counts on leaderboards, and per-user repost lists on profiles.
  
 */
export function subscribeAllReposts(callback: (data: RepostsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("reposts", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RepostsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Reposts collection at path '${"reposts"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Reposts items in collection reposts.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countReposts(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("reposts", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Reposts at path 'reposts': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Reposts items in collection reposts.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateReposts(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("reposts", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Reposts at path 'reposts': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Only the original reposter (@user.address == @data.reposterAddress) can delete their own repost, enabling un-repost behavior. Admin cannot delete on behalf of users.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteReposts(repostId: string): Promise<boolean> {
  try {
    const succeeded = await set(`reposts/${repostId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Reposts: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Reposts for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteReposts(repostId: string): DocumentOperation {
  return { path: `reposts/${repostId}`, document: null };
}

