// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: songStreams/$songId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks total stream count per song. Only backend (PROJECT_VAULT_ADDRESS) can create/increment to prevent users from inflating counts. Public readable for leaderboard display.
 */

export interface SongStreamsRequest {
  count: number | TimeOperation | IncrementOperation | TokenAmount;
  lastStreamedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SongStreamsResponse {
  count: number;
  lastStreamedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a SongStreams operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongStreams(songId: string, data: SongStreamsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `songStreams/${songId}`, document: doc };
}

/**
 * Only backend (signed with PROJECT_VAULT_ADDRESS) can create the initial stream record for a song. Frontend must call a backend route which validates and creates the record. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongStreams(songId: string, data: SongStreamsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`songStreams/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SongStreams: ${formatError(error)}`);
    return false;
  }
}

export type SongStreamsRequestUpdate = Partial<SongStreamsRequest>;

/**
 * Build a SongStreams update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateSongStreams(songId: string, data: SongStreamsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `songStreams/${songId}`, document: doc };
}

/**
 * Only backend (signed with PROJECT_VAULT_ADDRESS) can increment count and update lastStreamedAt. Prevents users from inflating their own counts. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateSongStreams(songId: string, data: SongStreamsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`songStreams/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating SongStreams: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read stream counts. Used for leaderboard and LiveChartCard display.
   (Get Single Item)
 */
export async function getSongStreams(songId: string): Promise<SongStreamsResponse | null> {
  try {
    const result = await get(`songStreams/${songId}`);
    return result as SongStreamsResponse | null;
  } catch (error) {
    console.error(`Error getting SongStreams: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SongStreams document. (
  Read Operation Details: Anyone can read stream counts. Used for leaderboard and LiveChartCard display.
  )
 */
export function subscribeSongStreams(callback: (data: SongStreamsResponse | null) => void, songId: string): Promise<() => Promise<void>> {
  return subscribe(`songStreams/${songId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongStreamsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SongStreams at path '${`songStreams/${songId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SongStreams items from collection songStreams
 
  Read Operation Details: Anyone can read stream counts. Used for leaderboard and LiveChartCard display.
  
 */
export async function getManySongStreams(filter: string = ""): Promise<SongStreamsResponse[]> {
  try {
    const results = await get("songStreams", { prompt: filter });
    return Array.isArray(results) ? results as SongStreamsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongStreams collection at path 'songStreams': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongStreams collection at songStreams
 
  Read Operation Details: Anyone can read stream counts. Used for leaderboard and LiveChartCard display.
  
 */
export function subscribeManySongStreams(callback: (data: SongStreamsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("songStreams", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongStreamsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongStreams collection at path '${"songStreams"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SongStreams items from collection songStreams
 
  Read Operation Details: Anyone can read stream counts. Used for leaderboard and LiveChartCard display.
  
 */
export async function getAllSongStreams(filter: string = ""): Promise<SongStreamsResponse[]> {
  try {
    const results = await get("songStreams", { prompt: filter });
    return Array.isArray(results) ? results as SongStreamsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SongStreams collection at path 'songStreams': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SongStreams collection at songStreams
 
  Read Operation Details: Anyone can read stream counts. Used for leaderboard and LiveChartCard display.
  
 */
export function subscribeAllSongStreams(callback: (data: SongStreamsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("songStreams", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongStreamsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SongStreams collection at path '${"songStreams"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SongStreams items in collection songStreams.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSongStreams(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("songStreams", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SongStreams at path 'songStreams': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SongStreams items in collection songStreams.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSongStreams(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("songStreams", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SongStreams at path 'songStreams': ${formatError(error)}`);
    return { value: 0 };
  }
}

