// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: streamEvents/$eventId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Individual song play/stream events for time-series analytics and listener behavior tracking.
 */

export interface StreamEventsRequest {
  songId: string;
  userAddress: AddressType;
  duration: number | TimeOperation | IncrementOperation | TokenAmount;
  timestamp: number | TimeOperation | IncrementOperation | TokenAmount;
  source: string;
}

export interface StreamEventsResponse {
  songId: string;
  userAddress: string;
  duration: number;
  timestamp: number;
  source: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a StreamEvents operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildStreamEvents(eventId: string, data: StreamEventsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `streamEvents/${eventId}`, document: doc };
}

/**
 * Authenticated users can log their own streams (userAddress must match caller wallet). Backend vault and operations wallet can also log on behalf of users. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setStreamEvents(eventId: string, data: StreamEventsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`streamEvents/${eventId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting StreamEvents: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Admin, project vault, and operations wallet only. Raw stream events used for time-series analytics dashboards.
   (Get Single Item)
 */
export async function getStreamEvents(eventId: string): Promise<StreamEventsResponse | null> {
  try {
    const result = await get(`streamEvents/${eventId}`);
    return result as StreamEventsResponse | null;
  } catch (error) {
    console.error(`Error getting StreamEvents: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single StreamEvents document. (
  Read Operation Details: Admin, project vault, and operations wallet only. Raw stream events used for time-series analytics dashboards.
  )
 */
export function subscribeStreamEvents(callback: (data: StreamEventsResponse | null) => void, eventId: string): Promise<() => Promise<void>> {
  return subscribe(`streamEvents/${eventId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as StreamEventsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to StreamEvents at path '${`streamEvents/${eventId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many StreamEvents items from collection streamEvents
 
  Read Operation Details: Admin, project vault, and operations wallet only. Raw stream events used for time-series analytics dashboards.
  
 */
export async function getManyStreamEvents(filter: string = ""): Promise<StreamEventsResponse[]> {
  try {
    const results = await get("streamEvents", { prompt: filter });
    return Array.isArray(results) ? results as StreamEventsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StreamEvents collection at path 'streamEvents': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StreamEvents collection at streamEvents
 
  Read Operation Details: Admin, project vault, and operations wallet only. Raw stream events used for time-series analytics dashboards.
  
 */
export function subscribeManyStreamEvents(callback: (data: StreamEventsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("streamEvents", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StreamEventsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StreamEvents collection at path '${"streamEvents"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all StreamEvents items from collection streamEvents
 
  Read Operation Details: Admin, project vault, and operations wallet only. Raw stream events used for time-series analytics dashboards.
  
 */
export async function getAllStreamEvents(filter: string = ""): Promise<StreamEventsResponse[]> {
  try {
    const results = await get("streamEvents", { prompt: filter });
    return Array.isArray(results) ? results as StreamEventsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StreamEvents collection at path 'streamEvents': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StreamEvents collection at streamEvents
 
  Read Operation Details: Admin, project vault, and operations wallet only. Raw stream events used for time-series analytics dashboards.
  
 */
export function subscribeAllStreamEvents(callback: (data: StreamEventsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("streamEvents", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StreamEventsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StreamEvents collection at path '${"streamEvents"}': ${formatError(error)}`);
    }
  });
}

