// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: usernames/$username
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Uniqueness-enforcing reverse lookup table mapping usernames to wallet addresses.
 */

export interface UsernamesRequest {
  userAddress: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface UsernamesResponse {
  userAddress: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Usernames operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUsernames(username: string, data: UsernamesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `usernames/${username}`, document: doc };
}

/**
 * Users can claim a username by creating a document with their wallet address as userAddress. Backend (PROJECT_VAULT_ADDRESS, OPERATIONS_WALLET) and ADMIN_ADDRESS can also create username mappings. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setUsernames(username: string, data: UsernamesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`usernames/${username}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Usernames: ${formatError(error)}`);
    return false;
  }
}

export type UsernamesRequestUpdate = Partial<UsernamesRequest>;

/**
 * Build a Usernames update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateUsernames(username: string, data: UsernamesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `usernames/${username}`, document: doc };
}

/**
 * Username mapping can be updated by the owner of the wallet address, or by backend/admin accounts. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateUsernames(username: string, data: UsernamesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`usernames/${username}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Usernames: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can look up which wallet address owns a username.
   (Get Single Item)
 */
export async function getUsernames(username: string): Promise<UsernamesResponse | null> {
  try {
    const result = await get(`usernames/${username}`);
    return result as UsernamesResponse | null;
  } catch (error) {
    console.error(`Error getting Usernames: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Usernames document. (
  Read Operation Details: Public read. Anyone can look up which wallet address owns a username.
  )
 */
export function subscribeUsernames(callback: (data: UsernamesResponse | null) => void, username: string): Promise<() => Promise<void>> {
  return subscribe(`usernames/${username}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as UsernamesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Usernames at path '${`usernames/${username}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Usernames items from collection usernames
 
  Read Operation Details: Public read. Anyone can look up which wallet address owns a username.
  
 */
export async function getManyUsernames(filter: string = ""): Promise<UsernamesResponse[]> {
  try {
    const results = await get("usernames", { prompt: filter });
    return Array.isArray(results) ? results as UsernamesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Usernames collection at path 'usernames': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Usernames collection at usernames
 
  Read Operation Details: Public read. Anyone can look up which wallet address owns a username.
  
 */
export function subscribeManyUsernames(callback: (data: UsernamesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("usernames", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UsernamesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Usernames collection at path '${"usernames"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Usernames items from collection usernames
 
  Read Operation Details: Public read. Anyone can look up which wallet address owns a username.
  
 */
export async function getAllUsernames(filter: string = ""): Promise<UsernamesResponse[]> {
  try {
    const results = await get("usernames", { prompt: filter });
    return Array.isArray(results) ? results as UsernamesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Usernames collection at path 'usernames': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Usernames collection at usernames
 
  Read Operation Details: Public read. Anyone can look up which wallet address owns a username.
  
 */
export function subscribeAllUsernames(callback: (data: UsernamesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("usernames", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UsernamesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Usernames collection at path '${"usernames"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Usernames items in collection usernames.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countUsernames(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("usernames", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Usernames at path 'usernames': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Usernames items in collection usernames.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateUsernames(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("usernames", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Usernames at path 'usernames': ${formatError(error)}`);
    return { value: 0 };
  }
}

