// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.094Z
// Collection: users/$userAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * User profiles with email linkage for Shopify webhook matching and token airdrop delivery.
 */

export interface UsersRequest {
  displayName?: string;
  email?: string;
  walletAddress: AddressType;
  profileImage?: string;
  username?: string;
  twitter?: string;
  instagram?: string;
  spotify?: string;
  tiktok?: string;
  youtube?: string;
  twitch?: string;
  kick?: string;
  soundcloud?: string;
  facebook?: string;
  linkedin?: string;
  telegram?: string;
  website?: string;
}

export interface UsersResponse {
  displayName?: string;
  email?: string;
  walletAddress: string;
  profileImage?: string;
  username?: string;
  twitter?: string;
  instagram?: string;
  spotify?: string;
  tiktok?: string;
  youtube?: string;
  twitch?: string;
  kick?: string;
  soundcloud?: string;
  facebook?: string;
  linkedin?: string;
  telegram?: string;
  website?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Users operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUsers(userAddress: string, data?: UsersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `users/${userAddress}`, document: doc };
}

/**
 * Users can create their own profile when $userAddress and walletAddress match their wallet. The backend (PROJECT_VAULT_ADDRESS) and ADMIN_ADDRESS can also create user records for new card-purchase wallets or administrative purposes. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setUsers(userAddress: string, data?: UsersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`users/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Users: ${formatError(error)}`);
    return false;
  }
}

export type UsersRequestUpdate = Partial<UsersRequest>;

/**
 * Build a Users update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateUsers(userAddress: string, data: UsersRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `users/${userAddress}`, document: doc };
}

/**
 * Users can update their own profile. PROJECT_VAULT_ADDRESS, OPERATIONS_WALLET, and ADMIN_ADDRESS can also update user records. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateUsers(userAddress: string, data: UsersRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`users/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Users: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Public read. Anyone can view user profiles.
   (Get Single Item)
 */
export async function getUsers(userAddress: string): Promise<UsersResponse | null> {
  try {
    const result = await get(`users/${userAddress}`);
    return result as UsersResponse | null;
  } catch (error) {
    console.error(`Error getting Users: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Users document. (
  Read Operation Details: Public read. Anyone can view user profiles.
  )
 */
export function subscribeUsers(callback: (data: UsersResponse | null) => void, userAddress: string): Promise<() => Promise<void>> {
  return subscribe(`users/${userAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as UsersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Users at path '${`users/${userAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Users items from collection users
 
  Read Operation Details: Public read. Anyone can view user profiles.
  
 */
export async function getManyUsers(filter: string = ""): Promise<UsersResponse[]> {
  try {
    const results = await get("users", { prompt: filter });
    return Array.isArray(results) ? results as UsersResponse[] : [];
  } catch (error) {
    console.error(`Error getting Users collection at path 'users': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Users collection at users
 
  Read Operation Details: Public read. Anyone can view user profiles.
  
 */
export function subscribeManyUsers(callback: (data: UsersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("users", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UsersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Users collection at path '${"users"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Users items from collection users
 
  Read Operation Details: Public read. Anyone can view user profiles.
  
 */
export async function getAllUsers(filter: string = ""): Promise<UsersResponse[]> {
  try {
    const results = await get("users", { prompt: filter });
    return Array.isArray(results) ? results as UsersResponse[] : [];
  } catch (error) {
    console.error(`Error getting Users collection at path 'users': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Users collection at users
 
  Read Operation Details: Public read. Anyone can view user profiles.
  
 */
export function subscribeAllUsers(callback: (data: UsersResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("users", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UsersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Users collection at path '${"users"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Users items in collection users.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countUsers(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("users", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Users at path 'users': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Users items in collection users.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateUsers(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("users", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Users at path 'users': ${formatError(error)}`);
    return { value: 0 };
  }
}

