// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.095Z
// Collection: userRealizedPnL/$userAddress/events/$eventId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks each realized gain/loss event when tokens are sold. Created by frontend after successful sells/swaps. Immutable once recorded.
 */

export interface UserRealizedPnLEventsRequest {
  tokenMint: AddressType;
  songId: string;
  songName: string;
  songSymbol: string;
  lotIds: string;
  totalSoldQuantity: number | TimeOperation | IncrementOperation | TokenAmount;
  totalCostBasis: number | TimeOperation | IncrementOperation | TokenAmount;
  totalSaleProceeds: number | TimeOperation | IncrementOperation | TokenAmount;
  currency: string;
  realizedPnL: number | IncrementOperation | TokenAmount;
  realizedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  source: string;
  txSignature: string;
}

export interface UserRealizedPnLEventsResponse {
  tokenMint: string;
  songId: string;
  songName: string;
  songSymbol: string;
  lotIds: string;
  totalSoldQuantity: number;
  totalCostBasis: number;
  totalSaleProceeds: number;
  currency: string;
  realizedPnL: number;
  realizedAt: number;
  source: string;
  txSignature: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a UserRealizedPnLEvents operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUserRealizedPnLEvents(userAddress: string, eventId: string, data?: UserRealizedPnLEventsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `userRealizedPnL/${userAddress}/events/${eventId}`, document: doc };
}

/**
 * Authenticated users only. Caller must equal $userAddress. Frontend creates a PnL event after each successful sell, calculating gain/loss from consumed lots. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setUserRealizedPnLEvents(userAddress: string, eventId: string, data?: UserRealizedPnLEventsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`userRealizedPnL/${userAddress}/events/${eventId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting UserRealizedPnLEvents: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read realized PnL events. Public for portfolio transparency.
   (Get Single Item)
 */
export async function getUserRealizedPnLEvents(userAddress: string, eventId: string): Promise<UserRealizedPnLEventsResponse | null> {
  try {
    const result = await get(`userRealizedPnL/${userAddress}/events/${eventId}`);
    return result as UserRealizedPnLEventsResponse | null;
  } catch (error) {
    console.error(`Error getting UserRealizedPnLEvents: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single UserRealizedPnLEvents document. (
  Read Operation Details: Anyone can read realized PnL events. Public for portfolio transparency.
  )
 */
export function subscribeUserRealizedPnLEvents(callback: (data: UserRealizedPnLEventsResponse | null) => void, userAddress: string, eventId: string): Promise<() => Promise<void>> {
  return subscribe(`userRealizedPnL/${userAddress}/events/${eventId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as UserRealizedPnLEventsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to UserRealizedPnLEvents at path '${`userRealizedPnL/${userAddress}/events/${eventId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many UserRealizedPnLEvents items from collection userRealizedPnL/${userAddress}/events
 
  Read Operation Details: Anyone can read realized PnL events. Public for portfolio transparency.
  
 */
export async function getManyUserRealizedPnLEvents(userAddress: string, filter: string = ""): Promise<UserRealizedPnLEventsResponse[]> {
  try {
    const results = await get(`userRealizedPnL/${userAddress}/events`, { prompt: filter });
    return Array.isArray(results) ? results as UserRealizedPnLEventsResponse[] : [];
  } catch (error) {
    console.error(`Error getting UserRealizedPnLEvents collection at path 'userRealizedPnL/${userAddress}/events': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in UserRealizedPnLEvents collection at userRealizedPnL/${userAddress}/events
 
  Read Operation Details: Anyone can read realized PnL events. Public for portfolio transparency.
  
 */
export function subscribeManyUserRealizedPnLEvents(callback: (data: UserRealizedPnLEventsResponse[]) => void, userAddress: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`userRealizedPnL/${userAddress}/events`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UserRealizedPnLEventsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to UserRealizedPnLEvents collection at path '${`userRealizedPnL/${userAddress}/events`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all UserRealizedPnLEvents items from collection userRealizedPnL/${userAddress}/events
 
  Read Operation Details: Anyone can read realized PnL events. Public for portfolio transparency.
  
 */
export async function getAllUserRealizedPnLEvents(userAddress: string, filter: string = ""): Promise<UserRealizedPnLEventsResponse[]> {
  try {
    const results = await get(`userRealizedPnL/*/events`, { prompt: filter });
    return Array.isArray(results) ? results as UserRealizedPnLEventsResponse[] : [];
  } catch (error) {
    console.error(`Error getting UserRealizedPnLEvents collection at path 'userRealizedPnL/${userAddress}/events': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in UserRealizedPnLEvents collection at userRealizedPnL/${userAddress}/events
 
  Read Operation Details: Anyone can read realized PnL events. Public for portfolio transparency.
  
 */
export function subscribeAllUserRealizedPnLEvents(callback: (data: UserRealizedPnLEventsResponse[]) => void, userAddress: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`userRealizedPnL/*/events`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as UserRealizedPnLEventsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to UserRealizedPnLEvents collection at path '${`userRealizedPnL/*/events`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count UserRealizedPnLEvents items in collection userRealizedPnL/${userAddress}/events.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countUserRealizedPnLEvents(userAddress: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`userRealizedPnL/${userAddress}/events`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting UserRealizedPnLEvents at path 'userRealizedPnL/${userAddress}/events': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on UserRealizedPnLEvents items in collection userRealizedPnL/${userAddress}/events.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateUserRealizedPnLEvents(userAddress: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`userRealizedPnL/${userAddress}/events`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating UserRealizedPnLEvents at path 'userRealizedPnL/${userAddress}/events': ${formatError(error)}`);
    return { value: 0 };
  }
}

