// Generated by TaroBase SDK Generator: 2026-06-04T02:59:09.094Z
// Collection: wishlists/$walletAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * User wishlists for songs they want to buy. Keyed by user's wallet address for natural uniqueness, one wishlist per user. songIds stores a JSON-serialized array of song IDs.
 */

export interface WishlistsRequest {
  songIds: string;
  updatedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface WishlistsResponse {
  songIds: string;
  updatedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Wishlists operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildWishlists(walletAddress: string, data: WishlistsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `wishlists/${walletAddress}`, document: doc };
}

/**
 * Users can only create their own wishlist. The $walletAddress path param must equal the caller's wallet address. songIds is a JSON-serialized string array of song IDs. updatedAt is a Unix timestamp in seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setWishlists(walletAddress: string, data: WishlistsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`wishlists/${walletAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Wishlists: ${formatError(error)}`);
    return false;
  }
}

export type WishlistsRequestUpdate = Partial<WishlistsRequest>;

/**
 * Build a Wishlists update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateWishlists(walletAddress: string, data: WishlistsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `wishlists/${walletAddress}`, document: doc };
}

/**
 * Only the wishlist owner can update their wishlist to add or remove song IDs. songIds and updatedAt are mutable and should be updated together. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateWishlists(walletAddress: string, data: WishlistsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`wishlists/${walletAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Wishlists: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Private. Only the wishlist owner can read their own wishlist, enforced by matching $walletAddress path param to the caller's wallet.
   (Get Single Item)
 */
export async function getWishlists(walletAddress: string): Promise<WishlistsResponse | null> {
  try {
    const result = await get(`wishlists/${walletAddress}`);
    return result as WishlistsResponse | null;
  } catch (error) {
    console.error(`Error getting Wishlists: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Wishlists document. (
  Read Operation Details: Private. Only the wishlist owner can read their own wishlist, enforced by matching $walletAddress path param to the caller's wallet.
  )
 */
export function subscribeWishlists(callback: (data: WishlistsResponse | null) => void, walletAddress: string): Promise<() => Promise<void>> {
  return subscribe(`wishlists/${walletAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as WishlistsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Wishlists at path '${`wishlists/${walletAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Wishlists items from collection wishlists
 
  Read Operation Details: Private. Only the wishlist owner can read their own wishlist, enforced by matching $walletAddress path param to the caller's wallet.
  
 */
export async function getManyWishlists(filter: string = ""): Promise<WishlistsResponse[]> {
  try {
    const results = await get("wishlists", { prompt: filter });
    return Array.isArray(results) ? results as WishlistsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Wishlists collection at path 'wishlists': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Wishlists collection at wishlists
 
  Read Operation Details: Private. Only the wishlist owner can read their own wishlist, enforced by matching $walletAddress path param to the caller's wallet.
  
 */
export function subscribeManyWishlists(callback: (data: WishlistsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("wishlists", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as WishlistsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Wishlists collection at path '${"wishlists"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Wishlists items from collection wishlists
 
  Read Operation Details: Private. Only the wishlist owner can read their own wishlist, enforced by matching $walletAddress path param to the caller's wallet.
  
 */
export async function getAllWishlists(filter: string = ""): Promise<WishlistsResponse[]> {
  try {
    const results = await get("wishlists", { prompt: filter });
    return Array.isArray(results) ? results as WishlistsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Wishlists collection at path 'wishlists': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Wishlists collection at wishlists
 
  Read Operation Details: Private. Only the wishlist owner can read their own wishlist, enforced by matching $walletAddress path param to the caller's wallet.
  
 */
export function subscribeAllWishlists(callback: (data: WishlistsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("wishlists", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as WishlistsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Wishlists collection at path '${"wishlists"}': ${formatError(error)}`);
    }
  });
}

